//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcManager.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcManager.Tools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be disabled.
        /// </summary>
        public static string AcObject_CannotBeDisabled {
            get {
                return ResourceManager.GetString("AcObject_CannotBeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object can’t be moved.
        /// </summary>
        public static string AcObject_CannotBeMoved {
            get {
                return ResourceManager.GetString("AcObject_CannotBeMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t delete.
        /// </summary>
        public static string AcObject_CannotDelete {
            get {
                return ResourceManager.GetString("AcObject_CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t toggle.
        /// </summary>
        public static string AcObject_CannotToggle {
            get {
                return ResourceManager.GetString("AcObject_CannotToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t toggle: {0}.
        /// </summary>
        public static string AcObject_CannotToggleExt {
            get {
                return ResourceManager.GetString("AcObject_CannotToggleExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure there is no runned app working with object’s folder..
        /// </summary>
        public static string AcObject_Disabling_MakeSureNoRunnedApps {
            get {
                return ResourceManager.GetString("AcObject_Disabling_MakeSureNoRunnedApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID is wrong.
        /// </summary>
        public static string AcObject_IdIsWrong {
            get {
                return ResourceManager.GetString("AcObject_IdIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not valid anymore.
        /// </summary>
        public static string AcObject_NotValidAnymore {
            get {
                return ResourceManager.GetString("AcObject_NotValidAnymore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place is taken.
        /// </summary>
        public static string AcObject_PlaceIsTaken {
            get {
                return ResourceManager.GetString("AcObject_PlaceIsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is missing.
        /// </summary>
        public static string AcRootDirectory_Missing {
            get {
                return ResourceManager.GetString("AcRootDirectory_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory “{0}” is missing.
        /// </summary>
        public static string AcRootDirectory_MissingDirectory {
            get {
                return ResourceManager.GetString("AcRootDirectory_MissingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File “{0}” is missing.
        /// </summary>
        public static string AcRootDirectory_MissingFile {
            get {
                return ResourceManager.GetString("AcRootDirectory_MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is not defined.
        /// </summary>
        public static string AcRootDirectory_NotDefined {
            get {
                return ResourceManager.GetString("AcRootDirectory_NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AcRootDirectory is required.
        /// </summary>
        public static string AcRootDirectory_Required {
            get {
                return ResourceManager.GetString("AcRootDirectory_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car.
        /// </summary>
        public static string AdditionalContent_Car {
            get {
                return ResourceManager.GetString("AdditionalContent_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car skin.
        /// </summary>
        public static string AdditionalContent_CarSkin {
            get {
                return ResourceManager.GetString("AdditionalContent_CarSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to font.
        /// </summary>
        public static string AdditionalContent_Font {
            get {
                return ResourceManager.GetString("AdditionalContent_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to showroom.
        /// </summary>
        public static string AdditionalContent_Showroom {
            get {
                return ResourceManager.GetString("AdditionalContent_Showroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to track.
        /// </summary>
        public static string AdditionalContent_Track {
            get {
                return ResourceManager.GetString("AdditionalContent_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weather.
        /// </summary>
        public static string AdditionalContent_Weather {
            get {
                return ResourceManager.GetString("AdditionalContent_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied.
        /// </summary>
        public static string AppUpdater_AccessIsDenied {
            get {
                return ResourceManager.GetString("AppUpdater_AccessIsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t update app due to lack of permissions. Please, update it manually..
        /// </summary>
        public static string AppUpdater_AccessIsDenied_Commentary {
            get {
                return ResourceManager.GetString("AppUpdater_AccessIsDenied_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t update app due to lack of permissions..
        /// </summary>
        public static string AppUpdater_AccessIsDenied_Short {
            get {
                return ResourceManager.GetString("AppUpdater_AccessIsDenied_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t download information about latest version..
        /// </summary>
        public static string AppUpdater_CannotDownloadInformation {
            get {
                return ResourceManager.GetString("AppUpdater_CannotDownloadInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t load the new version.
        /// </summary>
        public static string AppUpdater_CannotLoad {
            get {
                return ResourceManager.GetString("AppUpdater_CannotLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure internet connection is working and app has write permissions to its folder..
        /// </summary>
        public static string AppUpdater_CannotLoad_Commentary {
            get {
                return ResourceManager.GetString("AppUpdater_CannotLoad_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t load the new version..
        /// </summary>
        public static string AppUpdater_CannotLoadShort {
            get {
                return ResourceManager.GetString("AppUpdater_CannotLoadShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t remove original file “{0}” to install update. Try to remove it manually and then run “{1}”..
        /// </summary>
        public static string AppUpdater_CannotUpdate_HelpNeeded {
            get {
                return ResourceManager.GetString("AppUpdater_CannotUpdate_HelpNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t process update: {0}. Try to install a new version manually, sorry..
        /// </summary>
        public static string AppUpdater_CannotUpdate_Message {
            get {
                return ResourceManager.GetString("AppUpdater_CannotUpdate_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t update app.
        /// </summary>
        public static string AppUpdater_CannotUpdateApp {
            get {
                return ResourceManager.GetString("AppUpdater_CannotUpdateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some unhandled error happened..
        /// </summary>
        public static string AppUpdater_UnhandledError {
            get {
                return ResourceManager.GetString("AppUpdater_UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpacked version doesn’t support auto-updating..
        /// </summary>
        public static string AppUpdater_UnpackedVersionMessage {
            get {
                return ResourceManager.GetString("AppUpdater_UnpackedVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        public static string AppUpdater_UpdateFailed {
            get {
                return ResourceManager.GetString("AppUpdater_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extractor wasn’t initialized.
        /// </summary>
        public static string ArchiveInstallator_InitializationFault {
            get {
                return ResourceManager.GetString("ArchiveInstallator_InitializationFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid.
        /// </summary>
        public static string ArchiveInstallator_PasswordIsInvalid {
            get {
                return ResourceManager.GetString("ArchiveInstallator_PasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string ArchiveInstallator_PasswordIsRequired {
            get {
                return ResourceManager.GetString("ArchiveInstallator_PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but {0} encryption isn’t supported.
        /// </summary>
        public static string ArchiveInstallator_UnsupportedEncryption {
            get {
                return ResourceManager.GetString("ArchiveInstallator_UnsupportedEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t find Steam ID.
        /// </summary>
        public static string CannotFindSteamId {
            get {
                return ResourceManager.GetString("CannotFindSteamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid location.
        /// </summary>
        public static string CarSetupObject_Load_InvalidLocation {
            get {
                return ResourceManager.GetString("CarSetupObject_Load_InvalidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left front.
        /// </summary>
        public static string CarSetupObject_TyresPressure_LeftFront {
            get {
                return ResourceManager.GetString("CarSetupObject_TyresPressure_LeftFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left rear.
        /// </summary>
        public static string CarSetupObject_TyresPressure_LeftRear {
            get {
                return ResourceManager.GetString("CarSetupObject_TyresPressure_LeftRear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right front.
        /// </summary>
        public static string CarSetupObject_TyresPressure_RightFront {
            get {
                return ResourceManager.GetString("CarSetupObject_TyresPressure_RightFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right rear.
        /// </summary>
        public static string CarSetupObject_TyresPressure_RightRear {
            get {
                return ResourceManager.GetString("CarSetupObject_TyresPressure_RightRear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t download file.
        /// </summary>
        public static string Common_CannotDownloadFile {
            get {
                return ResourceManager.GetString("Common_CannotDownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure Internet connection is available..
        /// </summary>
        public static string Common_CannotDownloadFile_Commentary {
            get {
                return ResourceManager.GetString("Common_CannotDownloadFile_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssettoCorsa.club is changed..
        /// </summary>
        public static string DirectLoader_AcClubChanged {
            get {
                return ResourceManager.GetString("DirectLoader_AcClubChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assetto-DB.com is changed..
        /// </summary>
        public static string DirectLoader_AssettoDbChanged {
            get {
                return ResourceManager.GetString("DirectLoader_AssettoDbChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Drive is changed..
        /// </summary>
        public static string DirectLoader_GoogleDriveChanged {
            get {
                return ResourceManager.GetString("DirectLoader_GoogleDriveChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RaceDepartment is changed..
        /// </summary>
        public static string DirectLoader_RdChanged {
            get {
                return ResourceManager.GetString("DirectLoader_RdChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursion detected.
        /// </summary>
        public static string DirectLoader_RecursionDetected {
            get {
                return ResourceManager.GetString("DirectLoader_RecursionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string DirectoryInstallator_FileNotFound {
            get {
                return ResourceManager.GetString("DirectoryInstallator_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Font.
        /// </summary>
        public static string FontObject_DeleteFont {
            get {
                return ResourceManager.GetString("FontObject_DeleteFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some cars which need this font. Are you sure you want to delete it?.
        /// </summary>
        public static string FontObject_Deleting_SomeCarsNeedThisFont {
            get {
                return ResourceManager.GetString("FontObject_Deleting_SomeCarsNeedThisFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Font.
        /// </summary>
        public static string FontObject_DisableFont {
            get {
                return ResourceManager.GetString("FontObject_DisableFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are some cars which need this font. Are you sure you want to disable it?.
        /// </summary>
        public static string FontObject_Disabling_SomeCarsNeedThisFont {
            get {
                return ResourceManager.GetString("FontObject_Disabling_SomeCarsNeedThisFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t rescan cars.
        /// </summary>
        public static string Fonts_RescanUsings {
            get {
                return ResourceManager.GetString("Fonts_RescanUsings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axle {0}.
        /// </summary>
        public static string Input_Axle {
            get {
                return ResourceManager.GetString("Input_Axle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button {0}.
        /// </summary>
        public static string Input_Button {
            get {
                return ResourceManager.GetString("Input_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Skin Preview.
        /// </summary>
        public static string Installator_KeepSkinPreview {
            get {
                return ResourceManager.GetString("Installator_KeepSkinPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Skins Previews.
        /// </summary>
        public static string Installator_KeepSkinsPreviews {
            get {
                return ResourceManager.GetString("Installator_KeepSkinsPreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep UI Information.
        /// </summary>
        public static string Installator_KeepUiInformation {
            get {
                return ResourceManager.GetString("Installator_KeepUiInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep UI Information &amp; Skin Preview.
        /// </summary>
        public static string Installator_KeepUiInformationAndSkinPreview {
            get {
                return ResourceManager.GetString("Installator_KeepUiInformationAndSkinPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep UI Information &amp; Skins Previews.
        /// </summary>
        public static string Installator_KeepUiInformationAndSkinsPreviews {
            get {
                return ResourceManager.GetString("Installator_KeepUiInformationAndSkinsPreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Existing First.
        /// </summary>
        public static string Installator_RemoveExistingFirst {
            get {
                return ResourceManager.GetString("Installator_RemoveExistingFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Everytything.
        /// </summary>
        public static string Installator_UpdateEverything {
            get {
                return ResourceManager.GetString("Installator_UpdateEverything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Locked.
        /// </summary>
        public static string JumpStart_CarLocked {
            get {
                return ResourceManager.GetString("JumpStart_CarLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriveThrough.
        /// </summary>
        public static string JumpStart_DriveThrough {
            get {
                return ResourceManager.GetString("JumpStart_DriveThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teleport To Pit.
        /// </summary>
        public static string JumpStart_TeleportToPit {
            get {
                return ResourceManager.GetString("JumpStart_TeleportToPit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship.
        /// </summary>
        public static string KunosCareer_Championship {
            get {
                return ResourceManager.GetString("KunosCareer_Championship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single events.
        /// </summary>
        public static string KunosCareer_SingleEvents {
            get {
                return ResourceManager.GetString("KunosCareer_SingleEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t connect to remote server.
        /// </summary>
        public static string LogHelper_CannotConnectToRemoteServer {
            get {
                return ResourceManager.GetString("LogHelper_CannotConnectToRemoteServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver model is probably missing.
        /// </summary>
        public static string LogHelper_DriverIsMissing {
            get {
                return ResourceManager.GetString("LogHelper_DriverIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid.
        /// </summary>
        public static string LogHelper_PasswordIsInvalid {
            get {
                return ResourceManager.GetString("LogHelper_PasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspension objects (SUSP_LF, SUSP_LR, …) are missing.
        /// </summary>
        public static string LogHelper_SuspensionIsMissing {
            get {
                return ResourceManager.GetString("LogHelper_SuspensionIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wheels objects (WHEEL_LF, WHEEL_LR, …) are missing.
        /// </summary>
        public static string LogHelper_WheelsAreMissing {
            get {
                return ResourceManager.GetString("LogHelper_WheelsAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported.
        /// </summary>
        public static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t Run.
        /// </summary>
        public static string OfficialStarter_CannotRun {
            get {
                return ResourceManager.GetString("OfficialStarter_CannotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t run the game.
        /// </summary>
        public static string OfficialStarter_CannotRunGame {
            get {
                return ResourceManager.GetString("OfficialStarter_CannotRunGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t restore non-patched version of original launcher. Please, [url=&quot;https://drive.google.com/file/d/0B6GfX1zRa8pOcUxlTlU2WWZZTWM/view?usp=drivesdk&quot;]restore it manually[/url]..
        /// </summary>
        public static string OfficialStarter_DownloadAndRestore {
            get {
                return ResourceManager.GetString("OfficialStarter_DownloadAndRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t use Official Starter: game is too old. Would you like to switch to Tricky Starter instead? You can always go to Settings/Drive and change it..
        /// </summary>
        public static string OfficialStarter_GameIsTooOld {
            get {
                return ResourceManager.GetString("OfficialStarter_GameIsTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original launcher is missing; please, change starter..
        /// </summary>
        public static string OfficialStarter_OriginalLauncherIsMissing {
            get {
                return ResourceManager.GetString("OfficialStarter_OriginalLauncherIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t restore non-patched version of original launcher. Please, restore it manually: you have to replace “AssettoCorsa.exe” with “AssettoCorsa_backup_sp.exe”..
        /// </summary>
        public static string OfficialStarter_RestoreLauncherManually {
            get {
                return ResourceManager.GetString("OfficialStarter_RestoreLauncherManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, restore original launcher and try again (or change starter)..
        /// </summary>
        public static string OfficialStarter_RestoreOriginalLauncher {
            get {
                return ResourceManager.GetString("OfficialStarter_RestoreOriginalLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, update AC or change Starter to something else..
        /// </summary>
        public static string OfficialStarter_UpdateAC {
            get {
                return ResourceManager.GetString("OfficialStarter_UpdateAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t access server.
        /// </summary>
        public static string Online_CannotAccessServer {
            get {
                return ResourceManager.GetString("Online_CannotAccessServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t load data.
        /// </summary>
        public static string Online_CannotLoadData {
            get {
                return ResourceManager.GetString("Online_CannotLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure internet-connection is working..
        /// </summary>
        public static string Online_CannotLoadData_Commentary {
            get {
                return ResourceManager.GetString("Online_CannotLoadData_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t parse address.
        /// </summary>
        public static string Online_CannotParseAddress {
            get {
                return ResourceManager.GetString("Online_CannotParseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting information directly….
        /// </summary>
        public static string Online_GettingInformationDirectly {
            get {
                return ResourceManager.GetString("Online_GettingInformationDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting information directly (second attempt)….
        /// </summary>
        public static string Online_GettingInformationDirectly_SecondAttempt {
            get {
                return ResourceManager.GetString("Online_GettingInformationDirectly_SecondAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning….
        /// </summary>
        public static string Online_Scanning {
            get {
                return ResourceManager.GetString("Online_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found.
        /// </summary>
        public static string Online_ScanningNothingFound {
            get {
                return ResourceManager.GetString("Online_ScanningNothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure server&apos;s address is correct and server itself is accessible..
        /// </summary>
        public static string Online_ScanningNothingFound_Commentary {
            get {
                return ResourceManager.GetString("Online_ScanningNothingFound_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning ({0}/{1}), {2} found….
        /// </summary>
        public static string Online_ScanningProgress {
            get {
                return ResourceManager.GetString("Online_ScanningProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} server.
        /// </summary>
        public static string Online_ScanningProgress_Found {
            get {
                return ResourceManager.GetString("Online_ScanningProgress_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is unavailable (ping failed).
        ///.
        /// </summary>
        public static string Online_Server_CannotPing {
            get {
                return ResourceManager.GetString("Online_Server_CannotPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t refresh server information.
        ///.
        /// </summary>
        public static string Online_Server_CannotRefresh {
            get {
                return ResourceManager.GetString("Online_Server_CannotRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car {0} is missing..
        /// </summary>
        public static string Online_Server_CarIsMissing {
            get {
                return ResourceManager.GetString("Online_Server_CarIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars {0} are missing..
        /// </summary>
        public static string Online_Server_CarsAreMissing {
            get {
                return ResourceManager.GetString("Online_Server_CarsAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars don’t match..
        /// </summary>
        public static string Online_Server_CarsDoNotMatch {
            get {
                return ResourceManager.GetString("Online_Server_CarsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string Online_Server_CountryNA {
            get {
                return ResourceManager.GetString("Online_Server_CountryNA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “[url=&quot;http://assetto-db.com/car/{0}&quot;]{0}[/url]”.
        /// </summary>
        public static string Online_Server_MissingCarBbCode {
            get {
                return ResourceManager.GetString("Online_Server_MissingCarBbCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to “[url=&quot;http://assetto-db.com/track/{0}&quot;]{0}[/url]”.
        /// </summary>
        public static string Online_Server_MissingTrackBbCode {
            get {
                return ResourceManager.GetString("Online_Server_MissingTrackBbCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented.
        ///.
        /// </summary>
        public static string Online_Server_NotImplemented {
            get {
                return ResourceManager.GetString("Online_Server_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ended.
        /// </summary>
        public static string Online_Server_SessionEnded {
            get {
                return ResourceManager.GetString("Online_Server_SessionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track {0} is missing..
        /// </summary>
        public static string Online_Server_TrackIsMissing {
            get {
                return ResourceManager.GetString("Online_Server_TrackIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is unavailable..
        /// </summary>
        public static string Online_Server_Unavailable {
            get {
                return ResourceManager.GetString("Online_Server_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled error..
        /// </summary>
        public static string Online_Server_UnhandledError {
            get {
                return ResourceManager.GetString("Online_Server_UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} lap.
        /// </summary>
        public static string Online_Session_LapsDuration {
            get {
                return ResourceManager.GetString("Online_Session_LapsDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to ping to find out HTTP port….
        /// </summary>
        public static string Online_TryingToFindOutHttpPort {
            get {
                return ResourceManager.GetString("Online_TryingToFindOutHttpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID is taken.
        /// </summary>
        public static string OnlineManage_IdIsTaken {
            get {
                return ResourceManager.GetString("OnlineManage_IdIsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t install plugin.
        /// </summary>
        public static string Plugins_CannotInstall {
            get {
                return ResourceManager.GetString("Plugins_CannotInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t save PP filter.
        /// </summary>
        public static string PpFilterObject_CannotSave {
            get {
                return ResourceManager.GetString("PpFilterObject_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure its file could be overwritten..
        /// </summary>
        public static string PpFilterObject_MakeSureCouldBeOverwritten {
            get {
                return ResourceManager.GetString("PpFilterObject_MakeSureCouldBeOverwritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t Do.
        /// </summary>
        public static string Presets_CannotDo {
            get {
                return ResourceManager.GetString("Presets_CannotDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, choose a file in initial directory or some subdirectory..
        /// </summary>
        public static string Presets_ChooseFileInInitialDirectory {
            get {
                return ResourceManager.GetString("Presets_ChooseFileInInitialDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets (*{0})|*{0}.
        /// </summary>
        public static string Presets_FileFilter {
            get {
                return ResourceManager.GetString("Presets_FileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t rename replays.
        /// </summary>
        public static string Replay_CannotRenameReplays {
            get {
                return ResourceManager.GetString("Replay_CannotRenameReplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure none of those files are busy at the moment..
        /// </summary>
        public static string Replay_CannotRenameReplays_Commentary {
            get {
                return ResourceManager.GetString("Replay_CannotRenameReplays_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t save replay.
        /// </summary>
        public static string ReplayHelper_CannotSaveReplay {
            get {
                return ResourceManager.GetString("ReplayHelper_CannotSaveReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t unsave replay.
        /// </summary>
        public static string ReplayHelper_CannotUnsaveReplay {
            get {
                return ResourceManager.GetString("ReplayHelper_CannotUnsaveReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Session.
        /// </summary>
        public static string ReplayObject_PreviousSession {
            get {
                return ResourceManager.GetString("ReplayObject_PreviousSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported format.
        /// </summary>
        public static string ReplayReader_UnsupportedFormat {
            get {
                return ResourceManager.GetString("ReplayReader_UnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car setup.
        /// </summary>
        public static string Shared_CarSetup {
            get {
                return ResourceManager.GetString("Shared_CarSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls preset.
        /// </summary>
        public static string Shared_ControlsPreset {
            get {
                return ResourceManager.GetString("Shared_ControlsPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Feedback preset.
        /// </summary>
        public static string Shared_ForceFeedbackPreset {
            get {
                return ResourceManager.GetString("Shared_ForceFeedbackPreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP filter.
        /// </summary>
        public static string Shared_PpFilter {
            get {
                return ResourceManager.GetString("Shared_PpFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Drive preset.
        /// </summary>
        public static string Shared_QuickDrivePreset {
            get {
                return ResourceManager.GetString("Shared_QuickDrivePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        public static string Shared_Replay {
            get {
                return ResourceManager.GetString("Shared_Replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string Shared_Weather {
            get {
                return ResourceManager.GetString("Shared_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t get shared entry.
        /// </summary>
        public static string SharingHelper_CannotGetShared {
            get {
                return ResourceManager.GetString("SharingHelper_CannotGetShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure Internet connection works..
        /// </summary>
        public static string SharingHelper_CannotGetShared_Commentary {
            get {
                return ResourceManager.GetString("SharingHelper_CannotGetShared_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t get shared entry, its type {0} is not supported.
        /// </summary>
        public static string SharingHelper_NotSupported {
            get {
                return ResourceManager.GetString("SharingHelper_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure you have the latest version of CM..
        /// </summary>
        public static string SharingHelper_NotSupported_Commentary {
            get {
                return ResourceManager.GetString("SharingHelper_NotSupported_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t toggle sound.
        /// </summary>
        public static string ShowroomObject_CannotToggleSound {
            get {
                return ResourceManager.GetString("ShowroomObject_CannotToggleSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure there is no runned app working with showroom’s sound files..
        /// </summary>
        public static string ShowroomObject_CannotToggleSound_Commentary {
            get {
                return ResourceManager.GetString("ShowroomObject_CannotToggleSound_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} pit.
        /// </summary>
        public static string TrackBaseObject_Specs_PitsNumber {
            get {
                return ResourceManager.GetString("TrackBaseObject_Specs_PitsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again..
        /// </summary>
        public static string TryAgainDot {
            get {
                return ResourceManager.GetString("TryAgainDot", resourceCulture);
            }
        }
    }
}
