//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcManager.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcManager.Tools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid location.
        /// </summary>
        internal static string CarSetupObject_Load_InvalidLocation {
            get {
                return ResourceManager.GetString("CarSetupObject_Load_InvalidLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left front.
        /// </summary>
        internal static string CarSetupObject_TyresPressure_LeftFront {
            get {
                return ResourceManager.GetString("CarSetupObject_TyresPressure_LeftFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left rear.
        /// </summary>
        internal static string CarSetupObject_TyresPressure_LeftRear {
            get {
                return ResourceManager.GetString("CarSetupObject_TyresPressure_LeftRear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right front.
        /// </summary>
        internal static string CarSetupObject_TyresPressure_RightFront {
            get {
                return ResourceManager.GetString("CarSetupObject_TyresPressure_RightFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right rear.
        /// </summary>
        internal static string CarSetupObject_TyresPressure_RightRear {
            get {
                return ResourceManager.GetString("CarSetupObject_TyresPressure_RightRear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Supported.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t Run.
        /// </summary>
        internal static string OfficialStarter_CannotRun {
            get {
                return ResourceManager.GetString("OfficialStarter_CannotRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t run the game.
        /// </summary>
        internal static string OfficialStarter_CannotRunGame {
            get {
                return ResourceManager.GetString("OfficialStarter_CannotRunGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t restore non-patched version of original launcher. Please, [url=&quot;https://drive.google.com/file/d/0B6GfX1zRa8pOcUxlTlU2WWZZTWM/view?usp=drivesdk&quot;]restore it manually[/url]..
        /// </summary>
        internal static string OfficialStarter_DownloadAndRestore {
            get {
                return ResourceManager.GetString("OfficialStarter_DownloadAndRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t use Official Starter: game is too old. Would you like to switch to Tricky Starter instead? You can always go to Settings/Drive and change it..
        /// </summary>
        internal static string OfficialStarter_GameIsTooOld {
            get {
                return ResourceManager.GetString("OfficialStarter_GameIsTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original launcher is missing; please, change starter..
        /// </summary>
        internal static string OfficialStarter_OriginalLauncherIsMissing {
            get {
                return ResourceManager.GetString("OfficialStarter_OriginalLauncherIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t restore non-patched version of original launcher. Please, restore it manually: you have to replace “AssettoCorsa.exe” with “AssettoCorsa_backup_sp.exe”..
        /// </summary>
        internal static string OfficialStarter_RestoreLauncherManually {
            get {
                return ResourceManager.GetString("OfficialStarter_RestoreLauncherManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, restore original launcher and try again (or change starter)..
        /// </summary>
        internal static string OfficialStarter_RestoreOriginalLauncher {
            get {
                return ResourceManager.GetString("OfficialStarter_RestoreOriginalLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, update AC or change Starter to something else..
        /// </summary>
        internal static string OfficialStarter_UpdateAC {
            get {
                return ResourceManager.GetString("OfficialStarter_UpdateAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t save replay.
        /// </summary>
        internal static string ReplayHelper_CannotSaveReplay {
            get {
                return ResourceManager.GetString("ReplayHelper_CannotSaveReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t unsave replay.
        /// </summary>
        internal static string ReplayHelper_CannotUnsaveReplay {
            get {
                return ResourceManager.GetString("ReplayHelper_CannotUnsaveReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again..
        /// </summary>
        internal static string TryAgainDot {
            get {
                return ResourceManager.GetString("TryAgainDot", resourceCulture);
            }
        }
    }
}
