//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcManager.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ControlsStrings {
        
        private static FirstFloor.ModernUI.CustomResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static FirstFloor.ModernUI.CustomResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    FirstFloor.ModernUI.CustomResourceManager temp = new FirstFloor.ModernUI.CustomResourceManager("AcManager.Controls.ControlsStrings", typeof(ControlsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author, version &amp; URL (Ctrl+click to follow the link if set).
        /// </summary>
        public static string AcObject_Author_Tooltip {
            get {
                return ResourceManager.GetString("AcObject_Author_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string AcObject_AuthorLabel {
            get {
                return ResourceManager.GetString("AcObject_AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t update preview.
        /// </summary>
        public static string AcObject_CannotUpdatePreview {
            get {
                return ResourceManager.GetString("AcObject_CannotUpdatePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were supposed to make at least one screenshot..
        /// </summary>
        public static string AcObject_CannotUpdatePreview_TrackCommentary {
            get {
                return ResourceManager.GetString("AcObject_CannotUpdatePreview_TrackCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand:.
        /// </summary>
        public static string AcObject_CarBrandLabel {
            get {
                return ResourceManager.GetString("AcObject_CarBrandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class:.
        /// </summary>
        public static string AcObject_CarClassLabel {
            get {
                return ResourceManager.GetString("AcObject_CarClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent:.
        /// </summary>
        public static string AcObject_CarParentLabel {
            get {
                return ResourceManager.GetString("AcObject_CarParentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent car (if set, this car will be a tuned version of it).
        /// </summary>
        public static string AcObject_CarParentLabel_Tooltip {
            get {
                return ResourceManager.GetString("AcObject_CarParentLabel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string AcObject_CityLabel {
            get {
                return ResourceManager.GetString("AcObject_CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string AcObject_ContryLabel {
            get {
                return ResourceManager.GetString("AcObject_ContryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {Error}:.
        /// </summary>
        public static string AcObject_ErrorsHeader {
            get {
                return ResourceManager.GetString("AcObject_ErrorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel.
        /// </summary>
        public static string AcObject_Fuel {
            get {
                return ResourceManager.GetString("AcObject_Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel:.
        /// </summary>
        public static string AcObject_FuelLabel {
            get {
                return ResourceManager.GetString("AcObject_FuelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specs:.
        /// </summary>
        public static string AcObject_SpecsLabel {
            get {
                return ResourceManager.GetString("AcObject_SpecsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Tags:.
        /// </summary>
        public static string AcObject_TrackGeoTagsLabel {
            get {
                return ResourceManager.GetString("AcObject_TrackGeoTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyres:.
        /// </summary>
        public static string AcObject_TyresLabel {
            get {
                return ResourceManager.GetString("AcObject_TyresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL:.
        /// </summary>
        public static string AcObject_UrlLabel {
            get {
                return ResourceManager.GetString("AcObject_UrlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AcObject_VersionLabel {
            get {
                return ResourceManager.GetString("AcObject_VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        public static string AcObject_YearLabel {
            get {
                return ResourceManager.GetString("AcObject_YearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year of production start.
        /// </summary>
        public static string AcObject_YearLabel_CarTooltip {
            get {
                return ResourceManager.GetString("AcObject_YearLabel_CarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Animation_Down {
            get {
                return ResourceManager.GetString("Animation_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade.
        /// </summary>
        public static string Animation_Fade {
            get {
                return ResourceManager.GetString("Animation_Fade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern.
        /// </summary>
        public static string Animation_Modern {
            get {
                return ResourceManager.GetString("Animation_Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Animation_Up {
            get {
                return ResourceManager.GetString("Animation_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoblip:.
        /// </summary>
        public static string Assists_AutoBlipLabel {
            get {
                return ResourceManager.GetString("Assists_AutoBlipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto clutch:.
        /// </summary>
        public static string Assists_AutoClutchLabel {
            get {
                return ResourceManager.GetString("Assists_AutoClutchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto shifter:.
        /// </summary>
        public static string Assists_AutoShifterLabel {
            get {
                return ResourceManager.GetString("Assists_AutoShifterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel:.
        /// </summary>
        public static string Assists_FuelLabel {
            get {
                return ResourceManager.GetString("Assists_FuelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assists:.
        /// </summary>
        public static string Assists_Header {
            get {
                return ResourceManager.GetString("Assists_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal line:.
        /// </summary>
        public static string Assists_IdealLineLabel {
            get {
                return ResourceManager.GetString("Assists_IdealLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stability control:.
        /// </summary>
        public static string Assists_StabilityControlLabel {
            get {
                return ResourceManager.GetString("Assists_StabilityControlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyre wear:.
        /// </summary>
        public static string Assists_TyreWearLabel {
            get {
                return ResourceManager.GetString("Assists_TyreWearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamer.
        /// </summary>
        public static string AssistsPreset_Gamer {
            get {
                return ResourceManager.GetString("AssistsPreset_Gamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intermediate.
        /// </summary>
        public static string AssistsPreset_Intermediate {
            get {
                return ResourceManager.GetString("AssistsPreset_Intermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pro.
        /// </summary>
        public static string AssistsPreset_Pro {
            get {
                return ResourceManager.GetString("AssistsPreset_Pro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In Custom Showroom.
        /// </summary>
        public static string Car_OpenInCustomShowroom {
            get {
                return ResourceManager.GetString("Car_OpenInCustomShowroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In Showroom.
        /// </summary>
        public static string Car_OpenInShowroom {
            get {
                return ResourceManager.GetString("Car_OpenInShowroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children will be moved to the new parent!.
        /// </summary>
        public static string CarParent_ChildrenWillBeMoved {
            get {
                return ResourceManager.GetString("CarParent_ChildrenWillBeMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Independent.
        /// </summary>
        public static string CarParent_MakeIndependent {
            get {
                return ResourceManager.GetString("CarParent_MakeIndependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Common_AreYouSure {
            get {
                return ResourceManager.GetString("Common_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Common_Cancelled {
            get {
                return ResourceManager.GetString("Common_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0} °C.
        /// </summary>
        public static string Common_CelsiusFormat {
            get {
                return ResourceManager.GetString("Common_CelsiusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  °C.
        /// </summary>
        public static string Common_CelsiusPostfix {
            get {
                return ResourceManager.GetString("Common_CelsiusPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Common_Change {
            get {
                return ResourceManager.GetString("Common_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Skin.
        /// </summary>
        public static string Common_ChangeSkin {
            get {
                return ResourceManager.GetString("Common_ChangeSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressing….
        /// </summary>
        public static string Common_Compressing {
            get {
                return ResourceManager.GetString("Common_Compressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Tools.
        /// </summary>
        public static string Common_DevTools {
            get {
                return ResourceManager.GetString("Common_DevTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading….
        /// </summary>
        public static string Common_Downloading {
            get {
                return ResourceManager.GetString("Common_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure:.
        /// </summary>
        public static string Common_ExposureLabel {
            get {
                return ResourceManager.GetString("Common_ExposureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  °F.
        /// </summary>
        public static string Common_FahrenheitPostfix {
            get {
                return ResourceManager.GetString("Common_FahrenheitPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string Common_FilterLabel {
            get {
                return ResourceManager.GetString("Common_FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Common_Finished {
            get {
                return ResourceManager.GetString("Common_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder “{0}” already exists. Overwrite files?.
        /// </summary>
        public static string Common_FolderExists {
            get {
                return ResourceManager.GetString("Common_FolderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  FPS.
        /// </summary>
        public static string Common_FpsPostfix {
            get {
                return ResourceManager.GetString("Common_FpsPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic.
        /// </summary>
        public static string Common_Generic {
            get {
                return ResourceManager.GetString("Common_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good news!.
        /// </summary>
        public static string Common_GoodNews {
            get {
                return ResourceManager.GetString("Common_GoodNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing….
        /// </summary>
        public static string Common_Installing {
            get {
                return ResourceManager.GetString("Common_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  lap.
        /// </summary>
        public static string Common_LapsPostfix {
            get {
                return ResourceManager.GetString("Common_LapsPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading….
        /// </summary>
        public static string Common_Loading {
            get {
                return ResourceManager.GetString("Common_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  m.
        /// </summary>
        public static string Common_MetersPostfix {
            get {
                return ResourceManager.GetString("Common_MetersPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ms.
        /// </summary>
        public static string Common_MillisecondsPostfix {
            get {
                return ResourceManager.GetString("Common_MillisecondsPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minute.
        /// </summary>
        public static string Common_MinutePostfix {
            get {
                return ResourceManager.GetString("Common_MinutePostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  min.
        /// </summary>
        public static string Common_MinutesPostfix {
            get {
                return ResourceManager.GetString("Common_MinutesPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Mode.
        /// </summary>
        public static string Common_OfflineMode {
            get {
                return ResourceManager.GetString("Common_OfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} opponent.
        /// </summary>
        public static string Common_OpponentsFormat {
            get {
                return ResourceManager.GetString("Common_OpponentsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  opponent.
        /// </summary>
        public static string Common_OpponentsPostfix {
            get {
                return ResourceManager.GetString("Common_OpponentsPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Common_Options {
            get {
                return ResourceManager.GetString("Common_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  point.
        /// </summary>
        public static string Common_PointsPostfix {
            get {
                return ResourceManager.GetString("Common_PointsPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing….
        /// </summary>
        public static string Common_Preparing {
            get {
                return ResourceManager.GetString("Common_Preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string Common_Presets {
            get {
                return ResourceManager.GetString("Common_Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  psi.
        /// </summary>
        public static string Common_PsiPostfix {
            get {
                return ResourceManager.GetString("Common_PsiPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended value: {0}%.
        /// </summary>
        public static string Common_RecommendedPercentageFormat {
            get {
                return ResourceManager.GetString("Common_RecommendedPercentageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Common_Reset {
            get {
                return ResourceManager.GetString("Common_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to recommended value.
        /// </summary>
        public static string Common_ResetToRecommendedValue {
            get {
                return ResourceManager.GetString("Common_ResetToRecommendedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  lap.
        /// </summary>
        public static string Common_RoundPostfix {
            get {
                return ResourceManager.GetString("Common_RoundPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  sec.
        /// </summary>
        public static string Common_SecondsPostfix {
            get {
                return ResourceManager.GetString("Common_SecondsPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Common_Settings {
            get {
                return ResourceManager.GetString("Common_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string Common_TryAgain {
            get {
                return ResourceManager.GetString("Common_TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpack {0}.
        /// </summary>
        public static string Common_Unpack {
            get {
                return ResourceManager.GetString("Common_Unpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved.
        /// </summary>
        public static string Common_Unsaved {
            get {
                return ResourceManager.GetString("Common_Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading….
        /// </summary>
        public static string Common_Uploading {
            get {
                return ResourceManager.GetString("Common_Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting….
        /// </summary>
        public static string Common_Waiting {
            get {
                return ResourceManager.GetString("Common_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in Presets.
        /// </summary>
        public static string Controls_BuiltInPresets {
            get {
                return ResourceManager.GetString("Controls_BuiltInPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear keyboard binding.
        /// </summary>
        public static string Controls_ClearKeyboardBinding {
            get {
                return ResourceManager.GetString("Controls_ClearKeyboardBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear wheel binding.
        /// </summary>
        public static string Controls_ClearWheelBinding {
            get {
                return ResourceManager.GetString("Controls_ClearWheelBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to assign.
        /// </summary>
        public static string Controls_ClickToAssign {
            get {
                return ResourceManager.GetString("Controls_ClickToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damper gain.
        /// </summary>
        public static string Controls_DamperGain {
            get {
                return ResourceManager.GetString("Controls_DamperGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set to 0 for Logitech G920, keep 1 for everything else.
        /// </summary>
        public static string Controls_DamperGain_Tooltip {
            get {
                return ResourceManager.GetString("Controls_DamperGain_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degress.
        /// </summary>
        public static string Controls_DegressLabel {
            get {
                return ResourceManager.GetString("Controls_DegressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects:.
        /// </summary>
        public static string Controls_EffectsHeader {
            get {
                return ResourceManager.GetString("Controls_EffectsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced understeer effect.
        /// </summary>
        public static string Controls_EnhancedUndersteer {
            get {
                return ResourceManager.GetString("Controls_EnhancedUndersteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experimental:.
        /// </summary>
        public static string Controls_ExperimentalHeader {
            get {
                return ResourceManager.GetString("Controls_ExperimentalHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Controls_FilterAxis {
            get {
                return ResourceManager.GetString("Controls_FilterAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gain.
        /// </summary>
        public static string Controls_Gain {
            get {
                return ResourceManager.GetString("Controls_Gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamma.
        /// </summary>
        public static string Controls_GammaAxis {
            get {
                return ResourceManager.GetString("Controls_GammaAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyroscopic effect.
        /// </summary>
        public static string Controls_GyroscopicEffect {
            get {
                return ResourceManager.GetString("Controls_GyroscopicEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        public static string Controls_InvertAxis {
            get {
                return ResourceManager.GetString("Controls_InvertAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerb effect.
        /// </summary>
        public static string Controls_KerbEffect {
            get {
                return ResourceManager.GetString("Controls_KerbEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard button.
        /// </summary>
        public static string Controls_KeyboardButton {
            get {
                return ResourceManager.GetString("Controls_KeyboardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load “{0}”? Current values will be replaced (but later could be restored from Recycle Bin)..
        /// </summary>
        public static string Controls_LoadPresetWarning {
            get {
                return ResourceManager.GetString("Controls_LoadPresetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum force.
        /// </summary>
        public static string Controls_MinimumForce {
            get {
                return ResourceManager.GetString("Controls_MinimumForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum damper level.
        /// </summary>
        public static string Controls_MinumumDamperLevel {
            get {
                return ResourceManager.GetString("Controls_MinumumDamperLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous:.
        /// </summary>
        public static string Controls_MiscellaneousHeader {
            get {
                return ResourceManager.GetString("Controls_MiscellaneousHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device: [b]{0}[/b].
        /// </summary>
        public static string Controls_Preview_Device {
            get {
                return ResourceManager.GetString("Controls_Preview_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices: [b]{0}[/b].
        /// </summary>
        public static string Controls_Preview_Devices {
            get {
                return ResourceManager.GetString("Controls_Preview_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input method: [b]{0}[/b].
        /// </summary>
        public static string Controls_Preview_InputMethod {
            get {
                return ResourceManager.GetString("Controls_Preview_InputMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string Controls_RangeFromAxis {
            get {
                return ResourceManager.GetString("Controls_RangeFromAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string Controls_RangeToAxis {
            get {
                return ResourceManager.GetString("Controls_RangeToAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road effect.
        /// </summary>
        public static string Controls_RoadEffect {
            get {
                return ResourceManager.GetString("Controls_RoadEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip FFB steps.
        /// </summary>
        public static string Controls_SkipFfbSteps {
            get {
                return ResourceManager.GetString("Controls_SkipFfbSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physics engine steps to skip in order to accomodate wheels with lower FF input buffer; if you’re expeciencing problems with CPU, increase it to 2-4, it might help.
        /// </summary>
        public static string Controls_SkipFfbSteps_Tooltip {
            get {
                return ResourceManager.GetString("Controls_SkipFfbSteps_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slip effect.
        /// </summary>
        public static string Controls_SlipEffect {
            get {
                return ResourceManager.GetString("Controls_SlipEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft lock.
        /// </summary>
        public static string Controls_SoftLock {
            get {
                return ResourceManager.GetString("Controls_SoftLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed sensitivity.
        /// </summary>
        public static string Controls_SpeedSensitivity {
            get {
                return ResourceManager.GetString("Controls_SpeedSensitivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steering wheel button.
        /// </summary>
        public static string Controls_SteeringWheelButton {
            get {
                return ResourceManager.GetString("Controls_SteeringWheelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock experimental options (be careful!).
        /// </summary>
        public static string Controls_UnlockExperimental {
            get {
                return ResourceManager.GetString("Controls_UnlockExperimental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Presets.
        /// </summary>
        public static string Controls_UserPresets {
            get {
                return ResourceManager.GetString("Controls_UserPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for input.
        /// </summary>
        public static string Controls_WaitingForInput {
            get {
                return ResourceManager.GetString("Controls_WaitingForInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string CustomShowroom_AmbientShadows_Brightness {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadows_Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t update ambient shadows.
        /// </summary>
        public static string CustomShowroom_AmbientShadows_CannotUpdate {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadows_CannotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffusion.
        /// </summary>
        public static string CustomShowroom_AmbientShadows_Diffusion {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadows_Diffusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade to edges.
        /// </summary>
        public static string CustomShowroom_AmbientShadows_FadeToEdges {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadows_FadeToEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide wheels.
        /// </summary>
        public static string CustomShowroom_AmbientShadows_HideWheels {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadows_HideWheels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations.
        /// </summary>
        public static string CustomShowroom_AmbientShadows_Iterations {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadows_Iterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading textures….
        /// </summary>
        public static string CustomShowroom_AmbientShadows_Reloading {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadows_Reloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset To Recommended Values.
        /// </summary>
        public static string CustomShowroom_AmbientShadows_Reset {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadows_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Ambient Shadows.
        /// </summary>
        public static string CustomShowroom_AmbientShadows_Update {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadows_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating shadows….
        /// </summary>
        public static string CustomShowroom_AmbientShadows_Updating {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadows_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambient Shadow.
        /// </summary>
        public static string CustomShowroom_AmbientShadowsHeader {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadowsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Is Encrypted.
        /// </summary>
        public static string CustomShowroom_AmbientShadowsSize_EncryptedData {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadowsSize_EncryptedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of the shadow will be saved to “data/ambient_shadows.ini”, but data is encrypted, so it won’t have any affect. Continue?.
        /// </summary>
        public static string CustomShowroom_AmbientShadowsSize_EncryptedDataMessage {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadowsSize_EncryptedDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit.
        /// </summary>
        public static string CustomShowroom_AmbientShadowsSize_Fit {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadowsSize_Fit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight size.
        /// </summary>
        public static string CustomShowroom_AmbientShadowsSize_Highlight {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadowsSize_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string CustomShowroom_AmbientShadowsSize_Reset {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadowsSize_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string CustomShowroom_AmbientShadowsSize_Save {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadowsSize_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string CustomShowroom_AmbientShadowsSizeHeader {
            get {
                return ResourceManager.GetString("CustomShowroom_AmbientShadowsSizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t export texture.
        /// </summary>
        public static string CustomShowroom_CannotExport {
            get {
                return ResourceManager.GetString("CustomShowroom_CannotExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t start Custom Showroom.
        /// </summary>
        public static string CustomShowroom_CannotStart {
            get {
                return ResourceManager.GetString("CustomShowroom_CannotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lights.
        /// </summary>
        public static string CustomShowroom_Control_Lights {
            get {
                return ResourceManager.GetString("CustomShowroom_Control_Lights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireframe.
        /// </summary>
        public static string CustomShowroom_Control_Wireframe {
            get {
                return ResourceManager.GetString("CustomShowroom_Control_Wireframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string CustomShowroom_ControlHeader {
            get {
                return ResourceManager.GetString("CustomShowroom_ControlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin editing mode.
        /// </summary>
        public static string CustomShowroom_EditingMode {
            get {
                return ResourceManager.GetString("CustomShowroom_EditingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use PSD, XCF, etc. instead if exists (Magick.NET addon is required).
        /// </summary>
        public static string CustomShowroom_EditingMode_Tooltip {
            get {
                return ResourceManager.GetString("CustomShowroom_EditingMode_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string CustomShowroom_Export {
            get {
                return ResourceManager.GetString("CustomShowroom_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading model….
        /// </summary>
        public static string CustomShowroom_Loading {
            get {
                return ResourceManager.GetString("CustomShowroom_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material name: [b]{0}[/b]
        ///Shader: [b]{1}[/b]
        ///
        ///Blend mode: [b]{2}[/b]
        ///Alpha test: [b]{3}[/b]
        ///Depth mode: [b]{4}[/b].
        /// </summary>
        public static string CustomShowroom_MaterialInformation {
            get {
                return ResourceManager.GetString("CustomShowroom_MaterialInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name: [b]{0}[/b]
        ///Class: [b]{1}[/b]
        ///
        ///Active: [b]{2}[/b]
        ///Renderable: [b]{3}[/b]
        ///Visible: [b]{4}[/b]
        ///
        ///Transparent: [b]{5}[/b]
        ///Casting Shadows: [b]{6}[/b]
        ///
        ///Layer: [b]{7}[/b]
        ///LOD In: [b]{8}[/b]
        ///LOD In: [b]{9}[/b]
        ///
        ///Material: [b]{10}[/b].
        /// </summary>
        public static string CustomShowroom_ObjectInformation {
            get {
                return ResourceManager.GetString("CustomShowroom_ObjectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material:.
        /// </summary>
        public static string CustomShowroom_Selected_MaterialLabel {
            get {
                return ResourceManager.GetString("CustomShowroom_Selected_MaterialLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string CustomShowroom_Selected_NameLabel {
            get {
                return ResourceManager.GetString("CustomShowroom_Selected_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textures:.
        /// </summary>
        public static string CustomShowroom_Selected_TexturesLabel {
            get {
                return ResourceManager.GetString("CustomShowroom_Selected_TexturesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string CustomShowroom_SelectedHeader {
            get {
                return ResourceManager.GetString("CustomShowroom_SelectedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shader properties:.
        /// </summary>
        public static string CustomShowroom_ShaderProperties {
            get {
                return ResourceManager.GetString("CustomShowroom_ShaderProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin.
        /// </summary>
        public static string CustomShowroom_SkinHeader {
            get {
                return ResourceManager.GetString("CustomShowroom_SkinHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS:.
        /// </summary>
        public static string CustomShowroom_Stats_FpsLabel {
            get {
                return ResourceManager.GetString("CustomShowroom_Stats_FpsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects:.
        /// </summary>
        public static string CustomShowroom_Stats_ObjectsLabel {
            get {
                return ResourceManager.GetString("CustomShowroom_Stats_ObjectsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangles:.
        /// </summary>
        public static string CustomShowroom_Stats_TrianglesLabel {
            get {
                return ResourceManager.GetString("CustomShowroom_Stats_TrianglesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stats.
        /// </summary>
        public static string CustomShowroom_StatsHeader {
            get {
                return ResourceManager.GetString("CustomShowroom_StatsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions:.
        /// </summary>
        public static string CustomShowroom_TextureDimensionsLabel {
            get {
                return ResourceManager.GetString("CustomShowroom_TextureDimensionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format:.
        /// </summary>
        public static string CustomShowroom_TextureFormatLabel {
            get {
                return ResourceManager.GetString("CustomShowroom_TextureFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture is missing!.
        /// </summary>
        public static string CustomShowroom_TextureIsMissing {
            get {
                return ResourceManager.GetString("CustomShowroom_TextureIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string CustomShowroom_TextureSizeLabel {
            get {
                return ResourceManager.GetString("CustomShowroom_TextureSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string CustomShowroom_TextureTypeLabel {
            get {
                return ResourceManager.GetString("CustomShowroom_TextureTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string CustomShowroom_Tools_Title {
            get {
                return ResourceManager.GetString("CustomShowroom_Tools_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Mapping.
        /// </summary>
        public static string CustomShowroom_ViewMapping {
            get {
                return ResourceManager.GetString("CustomShowroom_ViewMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in 1024×1024.
        /// </summary>
        public static string CustomShowroom_ViewMapping_1024 {
            get {
                return ResourceManager.GetString("CustomShowroom_ViewMapping_1024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in 2048×2048.
        /// </summary>
        public static string CustomShowroom_ViewMapping_2048 {
            get {
                return ResourceManager.GetString("CustomShowroom_ViewMapping_2048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in 4096×4096.
        /// </summary>
        public static string CustomShowroom_ViewMapping_4096 {
            get {
                return ResourceManager.GetString("CustomShowroom_ViewMapping_4096", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in 512×512.
        /// </summary>
        public static string CustomShowroom_ViewMapping_512 {
            get {
                return ResourceManager.GetString("CustomShowroom_ViewMapping_512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View in custom resolution.
        /// </summary>
        public static string CustomShowroom_ViewMapping_Custom {
            get {
                return ResourceManager.GetString("CustomShowroom_ViewMapping_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Texture Mapping.
        /// </summary>
        public static string CustomShowroom_ViewMapping_Export {
            get {
                return ResourceManager.GetString("CustomShowroom_ViewMapping_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t figure out dimensions.
        /// </summary>
        public static string CustomShowroom_ViewMapping_ParsingFailed {
            get {
                return ResourceManager.GetString("CustomShowroom_ViewMapping_ParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, use valid format for them..
        /// </summary>
        public static string CustomShowroom_ViewMapping_ParsingFailed_Commentary {
            get {
                return ResourceManager.GetString("CustomShowroom_ViewMapping_ParsingFailed_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions ([Width]×[Height]):.
        /// </summary>
        public static string CustomShowroom_ViewMapping_Prompt {
            get {
                return ResourceManager.GetString("CustomShowroom_ViewMapping_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select year or description and press OK; hold Ctrl to extend description instead of replacing it..
        /// </summary>
        public static string FindInformation_Description {
            get {
                return ResourceManager.GetString("FindInformation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close.
        /// </summary>
        public static string FindInformation_SaveAndClose {
            get {
                return ResourceManager.GetString("FindInformation_SaveAndClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Country.
        /// </summary>
        public static string FindInformation_SaveAsCountry {
            get {
                return ResourceManager.GetString("FindInformation_SaveAsCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Description.
        /// </summary>
        public static string FindInformation_SaveAsDescription {
            get {
                return ResourceManager.GetString("FindInformation_SaveAsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Year.
        /// </summary>
        public static string FindInformation_SaveAsYear {
            get {
                return ResourceManager.GetString("FindInformation_SaveAsYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t save image.
        /// </summary>
        public static string ImageViewer_CannotSave {
            get {
                return ResourceManager.GetString("ImageViewer_CannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageViewer_DefaultName {
            get {
                return ResourceManager.GetString("ImageViewer_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image As.
        /// </summary>
        public static string ImageViewer_Save_Title {
            get {
                return ResourceManager.GetString("ImageViewer_Save_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed: .
        /// </summary>
        public static string KunosCareer_CompletedLabel {
            get {
                return ResourceManager.GetString("KunosCareer_CompletedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} error.
        /// </summary>
        public static string KunosCareer_Error {
            get {
                return ResourceManager.GetString("KunosCareer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required series: {0}.
        /// </summary>
        public static string KunosCareer_RequiredSeries {
            get {
                return ResourceManager.GetString("KunosCareer_RequiredSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required series aren’t finished yet.
        /// </summary>
        public static string KunosCareer_RequiredSeriesAreNotFinishedYet {
            get {
                return ResourceManager.GetString("KunosCareer_RequiredSeriesAreNotFinishedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car is missing:.
        /// </summary>
        public static string Online_CarIsMissingLabel {
            get {
                return ResourceManager.GetString("Online_CarIsMissingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivers online:.
        /// </summary>
        public static string Online_DriversOnlineLabel {
            get {
                return ResourceManager.GetString("Online_DriversOnlineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Using {0}.
        /// </summary>
        public static string Online_JoinUsing {
            get {
                return ResourceManager.GetString("Online_JoinUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required.
        /// </summary>
        public static string Online_PasswordRequired {
            get {
                return ResourceManager.GetString("Online_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track is missing:.
        /// </summary>
        public static string Online_TrackIsMissingLabel {
            get {
                return ResourceManager.GetString("Online_TrackIsMissingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download And Install ({0}).
        /// </summary>
        public static string Plugins_DownloadAndInstall {
            get {
                return ResourceManager.GetString("Plugins_DownloadAndInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available, required app version is {0}..
        /// </summary>
        public static string Plugins_NotAvailable {
            get {
                return ResourceManager.GetString("Plugins_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update (New Version: {0}).
        /// </summary>
        public static string Plugins_Update {
            get {
                return ResourceManager.GetString("Plugins_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Preset.
        /// </summary>
        public static string Presets_Save {
            get {
                return ResourceManager.GetString("Presets_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current settings as preset (Ctrl+S).
        /// </summary>
        public static string Presets_Save_Tooltip {
            get {
                return ResourceManager.GetString("Presets_Save_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved Preset.
        /// </summary>
        public static string Presets_Unsaved {
            get {
                return ResourceManager.GetString("Presets_Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between controls presets.
        /// </summary>
        public static string QuickSwitches_ControlsPresets_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_ControlsPresets_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage (UI).
        /// </summary>
        public static string QuickSwitches_DamageUi {
            get {
                return ResourceManager.GetString("QuickSwitches_DamageUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display damage.
        /// </summary>
        public static string QuickSwitches_DamageUi_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_DamageUi_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev apps.
        /// </summary>
        public static string QuickSwitches_DevApps {
            get {
                return ResourceManager.GetString("QuickSwitches_DevApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable developer apps.
        /// </summary>
        public static string QuickSwitches_DevApps_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_DevApps_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure.
        /// </summary>
        public static string QuickSwitches_Exposure {
            get {
                return ResourceManager.GetString("QuickSwitches_Exposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness level.
        /// </summary>
        public static string QuickSwitches_Exposure_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_Exposure_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOV.
        /// </summary>
        public static string QuickSwitches_Fov {
            get {
                return ResourceManager.GetString("QuickSwitches_Fov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of view (vertical angle).
        /// </summary>
        public static string QuickSwitches_Fov_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_Fov_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free camera.
        /// </summary>
        public static string QuickSwitches_FreeCamera {
            get {
                return ResourceManager.GetString("QuickSwitches_FreeCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable free camera (press F7 on track).
        /// </summary>
        public static string QuickSwitches_FreeCamera_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_FreeCamera_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string QuickSwitches_Fullscreen {
            get {
                return ResourceManager.GetString("QuickSwitches_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen mode (for example, Shadowplay won’t work without it).
        /// </summary>
        public static string QuickSwitches_Fullscreen_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_Fullscreen_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Switches.
        /// </summary>
        public static string QuickSwitches_Header {
            get {
                return ResourceManager.GetString("QuickSwitches_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide arms.
        /// </summary>
        public static string QuickSwitches_HideArms {
            get {
                return ResourceManager.GetString("QuickSwitches_HideArms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide driver’s arms.
        /// </summary>
        public static string QuickSwitches_HideArms_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_HideArms_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide driver.
        /// </summary>
        public static string QuickSwitches_HideDriver {
            get {
                return ResourceManager.GetString("QuickSwitches_HideDriver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide driver model.
        /// </summary>
        public static string QuickSwitches_HideDriver_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_HideDriver_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide wheel.
        /// </summary>
        public static string QuickSwitches_HideWheel {
            get {
                return ResourceManager.GetString("QuickSwitches_HideWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide steering wheel.
        /// </summary>
        public static string QuickSwitches_HideWheel_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_HideWheel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string QuickSwitches_Leaderboard {
            get {
                return ResourceManager.GetString("QuickSwitches_Leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display leaderboard.
        /// </summary>
        public static string QuickSwitches_Leaderboard_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_Leaderboard_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock camera.
        /// </summary>
        public static string QuickSwitches_LockCamera {
            get {
                return ResourceManager.GetString("QuickSwitches_LockCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock onboard camera to horizon.
        /// </summary>
        public static string QuickSwitches_LockCamera_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_LockCamera_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock wheel.
        /// </summary>
        public static string QuickSwitches_LockWheel {
            get {
                return ResourceManager.GetString("QuickSwitches_LockWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock steering wheel.
        /// </summary>
        public static string QuickSwitches_LockWheel_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_LockWheel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror.
        /// </summary>
        public static string QuickSwitches_Mirror {
            get {
                return ResourceManager.GetString("QuickSwitches_Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display virtual mirror.
        /// </summary>
        public static string QuickSwitches_Mirror_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_Mirror_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string QuickSwitches_Names {
            get {
                return ResourceManager.GetString("QuickSwitches_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display drivers’ names.
        /// </summary>
        public static string QuickSwitches_Names_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_Names_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest.
        /// </summary>
        public static string QuickSwitches_Nearest {
            get {
                return ResourceManager.GetString("QuickSwitches_Nearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online name.
        /// </summary>
        public static string QuickSwitches_OnlineName {
            get {
                return ResourceManager.GetString("QuickSwitches_OnlineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use different name online.
        /// </summary>
        public static string QuickSwitches_OnlineName_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_OnlineName_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between PP filters.
        /// </summary>
        public static string QuickSwitches_PpFilters_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_PpFilters_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between UI presets.
        /// </summary>
        public static string QuickSwitches_UiPresets_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_UiPresets_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between video-settings presets.
        /// </summary>
        public static string QuickSwitches_VideoPresets_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_VideoPresets_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay will be overwritten after the next race. Rename it to keep it..
        /// </summary>
        public static string Replay_CrMessage {
            get {
                return ResourceManager.GetString("Replay_CrMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can go to Settings and enable “Save replays automatically” option to avoid losing something valuable..
        /// </summary>
        public static string Replay_CrMessage_Commentary {
            get {
                return ResourceManager.GetString("Replay_CrMessage_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t share {0}.
        /// </summary>
        public static string Share_CannotShare {
            get {
                return ResourceManager.GetString("Share_CannotShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter custom ID:.
        /// </summary>
        public static string Share_EnterCustomId {
            get {
                return ResourceManager.GetString("Share_EnterCustomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom ID.
        /// </summary>
        public static string Share_EnterCustomIdHeader {
            get {
                return ResourceManager.GetString("Share_EnterCustomIdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name or keep field empty:.
        /// </summary>
        public static string Share_EnterName {
            get {
                return ResourceManager.GetString("Share_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share As.
        /// </summary>
        public static string Share_EnterNameHeader {
            get {
                return ResourceManager.GetString("Share_EnterNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing….
        /// </summary>
        public static string Share_InProgress {
            get {
                return ResourceManager.GetString("Share_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Shared.
        /// </summary>
        public static string Share_Shared {
            get {
                return ResourceManager.GetString("Share_Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link copied to clipboard.
        /// </summary>
        public static string Share_SharedMessage {
            get {
                return ResourceManager.GetString("Share_SharedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open link.
        /// </summary>
        public static string Share_SharedMessageAlternative {
            get {
                return ResourceManager.GetString("Share_SharedMessageAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name: [b]{0}[/b]
        ///Entry name: [b]{1}[/b]
        ///Entry type: [b]{2}[/b].
        /// </summary>
        public static string Share_VerifyMessage {
            get {
                return ResourceManager.GetString("Share_VerifyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Everything OK?.
        /// </summary>
        public static string Share_VerifyMessageHeader {
            get {
                return ResourceManager.GetString("Share_VerifyMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t start showroom.
        /// </summary>
        public static string Showroom_CannotStart {
            get {
                return ResourceManager.GetString("Showroom_CannotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showroom.
        /// </summary>
        public static string Showroom_DialogHeader {
            get {
                return ResourceManager.GetString("Showroom_DialogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable SweetFX.
        /// </summary>
        public static string Showroom_DisableSweetFx {
            get {
                return ResourceManager.GetString("Showroom_DisableSweetFx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparantly SweetFX doesn’t affect the result, but could decrease loading time.
        /// </summary>
        public static string Showroom_DisableSweetFx_Tooltip {
            get {
                return ResourceManager.GetString("Showroom_DisableSweetFx_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOV:.
        /// </summary>
        public static string Showroom_FovLabel {
            get {
                return ResourceManager.GetString("Showroom_FovLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide watermark.
        /// </summary>
        public static string Showroom_HideWatermark {
            get {
                return ResourceManager.GetString("Showroom_HideWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunos watermark will be temporary hidden.
        /// </summary>
        public static string Showroom_HideWatermark_Tooltip {
            get {
                return ResourceManager.GetString("Showroom_HideWatermark_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showroom:.
        /// </summary>
        public static string Showroom_ShowroomLabel {
            get {
                return ResourceManager.GetString("Showroom_ShowroomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        public static string TableHeader_Ai {
            get {
                return ResourceManager.GetString("TableHeader_Ai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Lap.
        /// </summary>
        public static string TableHeader_BestLap {
            get {
                return ResourceManager.GetString("TableHeader_BestLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string TableHeader_Car {
            get {
                return ResourceManager.GetString("TableHeader_Car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin.
        /// </summary>
        public static string TableHeader_CarSkin {
            get {
                return ResourceManager.GetString("TableHeader_CarSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TableHeader_Date {
            get {
                return ResourceManager.GetString("TableHeader_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string TableHeader_Locked {
            get {
                return ResourceManager.GetString("TableHeader_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TableHeader_Name {
            get {
                return ResourceManager.GetString("TableHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string TableHeader_Nationality {
            get {
                return ResourceManager.GetString("TableHeader_Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string TableHeader_Track {
            get {
                return ResourceManager.GetString("TableHeader_Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string TableHeader_Visible {
            get {
                return ResourceManager.GetString("TableHeader_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        public static string TableHeader_X {
            get {
                return ResourceManager.GetString("TableHeader_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        public static string TableHeader_Y {
            get {
                return ResourceManager.GetString("TableHeader_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Theme_Black {
            get {
                return ResourceManager.GetString("Theme_Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nordschleife.
        /// </summary>
        public static string Theme_Nordschleife {
            get {
                return ResourceManager.GetString("Theme_Nordschleife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new ui_skin.json file (Alt+S).
        /// </summary>
        public static string Toolbar_CreateJson_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_CreateJson_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove ui_skin.json to Recycle Bin (Alt+Delete).
        /// </summary>
        public static string Toolbar_DeleteJson_Tooltip {
            get {
                return ResourceManager.GetString("Toolbar_DeleteJson_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t play video.
        /// </summary>
        public static string Video_CannotPlay {
            get {
                return ResourceManager.GetString("Video_CannotPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, go to the Settings and enable VLC addon..
        /// </summary>
        public static string Video_CannotPlay_Commentary {
            get {
                return ResourceManager.GetString("Video_CannotPlay_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t play video.
        /// </summary>
        public static string VideoViewer_CannotPlay {
            get {
                return ResourceManager.GetString("VideoViewer_CannotPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure VLC addon is installed properly..
        /// </summary>
        public static string VideoViewer_CannotPlay_Commentary {
            get {
                return ResourceManager.GetString("VideoViewer_CannotPlay_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpage says.
        /// </summary>
        public static string WebBrowser_Prompt {
            get {
                return ResourceManager.GetString("WebBrowser_Prompt", resourceCulture);
            }
        }
    }
}
