//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcManager.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcManager.Controls.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author, version &amp;amp; URL.
        /// </summary>
        public static string AcObject_AuthorTooltip {
            get {
                return ResourceManager.GetString("AcObject_AuthorTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand:.
        /// </summary>
        public static string AcObject_CarBrandLabel {
            get {
                return ResourceManager.GetString("AcObject_CarBrandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class:.
        /// </summary>
        public static string AcObject_CarClassLabel {
            get {
                return ResourceManager.GetString("AcObject_CarClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent:.
        /// </summary>
        public static string AcObject_CarParentLabel {
            get {
                return ResourceManager.GetString("AcObject_CarParentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City:.
        /// </summary>
        public static string AcObject_CityLabel {
            get {
                return ResourceManager.GetString("AcObject_CityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country:.
        /// </summary>
        public static string AcObject_ContryLabel {
            get {
                return ResourceManager.GetString("AcObject_ContryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors:.
        /// </summary>
        public static string AcObject_ErrorsHeader {
            get {
                return ResourceManager.GetString("AcObject_ErrorsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specs:.
        /// </summary>
        public static string AcObject_SpecsLabel {
            get {
                return ResourceManager.GetString("AcObject_SpecsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Tags:.
        /// </summary>
        public static string AcObject_TrackGeoTagsLabel {
            get {
                return ResourceManager.GetString("AcObject_TrackGeoTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year:.
        /// </summary>
        public static string AcObject_YearLabel {
            get {
                return ResourceManager.GetString("AcObject_YearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string Animation_Down {
            get {
                return ResourceManager.GetString("Animation_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fade.
        /// </summary>
        public static string Animation_Fade {
            get {
                return ResourceManager.GetString("Animation_Fade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern.
        /// </summary>
        public static string Animation_Modern {
            get {
                return ResourceManager.GetString("Animation_Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string Animation_Up {
            get {
                return ResourceManager.GetString("Animation_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABS:.
        /// </summary>
        public static string Assists_AbsLabel {
            get {
                return ResourceManager.GetString("Assists_AbsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto blip:.
        /// </summary>
        public static string Assists_AutoBlipLabel {
            get {
                return ResourceManager.GetString("Assists_AutoBlipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto clutch:.
        /// </summary>
        public static string Assists_AutoClutchLabel {
            get {
                return ResourceManager.GetString("Assists_AutoClutchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto shifter:.
        /// </summary>
        public static string Assists_AutoShifterLabel {
            get {
                return ResourceManager.GetString("Assists_AutoShifterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel:.
        /// </summary>
        public static string Assists_FuelLabel {
            get {
                return ResourceManager.GetString("Assists_FuelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assists:.
        /// </summary>
        public static string Assists_Header {
            get {
                return ResourceManager.GetString("Assists_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideal line:.
        /// </summary>
        public static string Assists_IdealLineLabel {
            get {
                return ResourceManager.GetString("Assists_IdealLineLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stability control:.
        /// </summary>
        public static string Assists_StabilityControlLabel {
            get {
                return ResourceManager.GetString("Assists_StabilityControlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC:.
        /// </summary>
        public static string Assists_TractionControlLabel {
            get {
                return ResourceManager.GetString("Assists_TractionControlLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyre wear:.
        /// </summary>
        public static string Assists_TyreWearLabel {
            get {
                return ResourceManager.GetString("Assists_TyreWearLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In Custom Showroom.
        /// </summary>
        public static string Car_OpenInCustomShowroom {
            get {
                return ResourceManager.GetString("Car_OpenInCustomShowroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In Showroom.
        /// </summary>
        public static string Car_OpenInShowroom {
            get {
                return ResourceManager.GetString("Car_OpenInShowroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Common_AreYouSure {
            get {
                return ResourceManager.GetString("Common_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string Common_FilterLabel {
            get {
                return ResourceManager.GetString("Common_FilterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        public static string Common_Oops {
            get {
                return ResourceManager.GetString("Common_Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string Common_Presets {
            get {
                return ResourceManager.GetString("Common_Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Common_Settings {
            get {
                return ResourceManager.GetString("Common_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in Presets.
        /// </summary>
        public static string Controls_BuiltInPresets {
            get {
                return ResourceManager.GetString("Controls_BuiltInPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load “{0}”? Current values will be replaced (but later could be restored from Recycle Bin)..
        /// </summary>
        public static string Controls_LoadPresetWarning {
            get {
                return ResourceManager.GetString("Controls_LoadPresetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device: [b]{0}[/b].
        /// </summary>
        public static string Controls_Preview_Device {
            get {
                return ResourceManager.GetString("Controls_Preview_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices: [b]{0}[/b].
        /// </summary>
        public static string Controls_Preview_Devices {
            get {
                return ResourceManager.GetString("Controls_Preview_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input method: [b]{0}[/b].
        /// </summary>
        public static string Controls_Preview_InputMethod {
            get {
                return ResourceManager.GetString("Controls_Preview_InputMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Presets.
        /// </summary>
        public static string Controls_UserPresets {
            get {
                return ResourceManager.GetString("Controls_UserPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed: .
        /// </summary>
        public static string KunosCareer_CompletedLabel {
            get {
                return ResourceManager.GetString("KunosCareer_CompletedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} error.
        /// </summary>
        public static string KunosCareer_Error {
            get {
                return ResourceManager.GetString("KunosCareer_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to point.
        /// </summary>
        public static string KunosCareer_Point {
            get {
                return ResourceManager.GetString("KunosCareer_Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required series: {0}.
        /// </summary>
        public static string KunosCareer_RequiredSeries {
            get {
                return ResourceManager.GetString("KunosCareer_RequiredSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required series aren’t finished yet.
        /// </summary>
        public static string KunosCareer_RequiredSeriesAreNotFinishedYet {
            get {
                return ResourceManager.GetString("KunosCareer_RequiredSeriesAreNotFinishedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Preset.
        /// </summary>
        public static string Presets_Save {
            get {
                return ResourceManager.GetString("Presets_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current settings as preset.
        /// </summary>
        public static string Presets_Save_Tooltip {
            get {
                return ResourceManager.GetString("Presets_Save_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved.
        /// </summary>
        public static string Presets_Unsaved {
            get {
                return ResourceManager.GetString("Presets_Unsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between controls presets.
        /// </summary>
        public static string QuickSwitches_ControlsPresets_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_ControlsPresets_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Damage (UI).
        /// </summary>
        public static string QuickSwitches_DamageUi {
            get {
                return ResourceManager.GetString("QuickSwitches_DamageUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display damage.
        /// </summary>
        public static string QuickSwitches_DamageUi_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_DamageUi_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev apps.
        /// </summary>
        public static string QuickSwitches_DevApps {
            get {
                return ResourceManager.GetString("QuickSwitches_DevApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable developer apps.
        /// </summary>
        public static string QuickSwitches_DevApps_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_DevApps_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure.
        /// </summary>
        public static string QuickSwitches_Exposure {
            get {
                return ResourceManager.GetString("QuickSwitches_Exposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness level.
        /// </summary>
        public static string QuickSwitches_Exposure_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_Exposure_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FOV.
        /// </summary>
        public static string QuickSwitches_Fov {
            get {
                return ResourceManager.GetString("QuickSwitches_Fov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of view (vertical angle).
        /// </summary>
        public static string QuickSwitches_Fov_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_Fov_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free camera.
        /// </summary>
        public static string QuickSwitches_FreeCamera {
            get {
                return ResourceManager.GetString("QuickSwitches_FreeCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable free camera (press F7 in-game).
        /// </summary>
        public static string QuickSwitches_FreeCamera_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_FreeCamera_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string QuickSwitches_Fullscreen {
            get {
                return ResourceManager.GetString("QuickSwitches_Fullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen mode (for example, Shadowplay won’t work without it).
        /// </summary>
        public static string QuickSwitches_Fullscreen_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_Fullscreen_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Switches.
        /// </summary>
        public static string QuickSwitches_Header {
            get {
                return ResourceManager.GetString("QuickSwitches_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide arms.
        /// </summary>
        public static string QuickSwitches_HideArms {
            get {
                return ResourceManager.GetString("QuickSwitches_HideArms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide driver’s arms.
        /// </summary>
        public static string QuickSwitches_HideArms_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_HideArms_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide wheel.
        /// </summary>
        public static string QuickSwitches_HideWheel {
            get {
                return ResourceManager.GetString("QuickSwitches_HideWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide steering wheel.
        /// </summary>
        public static string QuickSwitches_HideWheel_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_HideWheel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboard.
        /// </summary>
        public static string QuickSwitches_Leaderboard {
            get {
                return ResourceManager.GetString("QuickSwitches_Leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display leaderboard.
        /// </summary>
        public static string QuickSwitches_Leaderboard_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_Leaderboard_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock camera.
        /// </summary>
        public static string QuickSwitches_LockCamera {
            get {
                return ResourceManager.GetString("QuickSwitches_LockCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock onboard camera to horizon.
        /// </summary>
        public static string QuickSwitches_LockCamera_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_LockCamera_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock wheel.
        /// </summary>
        public static string QuickSwitches_LockWheel {
            get {
                return ResourceManager.GetString("QuickSwitches_LockWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock steering wheel.
        /// </summary>
        public static string QuickSwitches_LockWheel_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_LockWheel_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror.
        /// </summary>
        public static string QuickSwitches_Mirror {
            get {
                return ResourceManager.GetString("QuickSwitches_Mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display virtual mirror.
        /// </summary>
        public static string QuickSwitches_Mirror_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_Mirror_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names.
        /// </summary>
        public static string QuickSwitches_Names {
            get {
                return ResourceManager.GetString("QuickSwitches_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display drivers’ names.
        /// </summary>
        public static string QuickSwitches_Names_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_Names_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nearest.
        /// </summary>
        public static string QuickSwitches_Nearest {
            get {
                return ResourceManager.GetString("QuickSwitches_Nearest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online name.
        /// </summary>
        public static string QuickSwitches_OnlineName {
            get {
                return ResourceManager.GetString("QuickSwitches_OnlineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use different name online.
        /// </summary>
        public static string QuickSwitches_OnlineName_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_OnlineName_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between PP filters.
        /// </summary>
        public static string QuickSwitches_PpFilters_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_PpFilters_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between UI presets.
        /// </summary>
        public static string QuickSwitches_UiPresets_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_UiPresets_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between video-settings presets.
        /// </summary>
        public static string QuickSwitches_VideoPresets_Tooltip {
            get {
                return ResourceManager.GetString("QuickSwitches_VideoPresets_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t share {0}.
        /// </summary>
        public static string Share_CannotShare {
            get {
                return ResourceManager.GetString("Share_CannotShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure Internet connection is available..
        /// </summary>
        public static string Share_CannotShare_Commentary {
            get {
                return ResourceManager.GetString("Share_CannotShare_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter custom ID:.
        /// </summary>
        public static string Share_EnterCustomId {
            get {
                return ResourceManager.GetString("Share_EnterCustomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom ID.
        /// </summary>
        public static string Share_EnterCustomIdHeader {
            get {
                return ResourceManager.GetString("Share_EnterCustomIdHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name or keep field empty:.
        /// </summary>
        public static string Share_EnterName {
            get {
                return ResourceManager.GetString("Share_EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share As.
        /// </summary>
        public static string Share_EnterNameHeader {
            get {
                return ResourceManager.GetString("Share_EnterNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing….
        /// </summary>
        public static string Share_InProgress {
            get {
                return ResourceManager.GetString("Share_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Shared.
        /// </summary>
        public static string Share_Shared {
            get {
                return ResourceManager.GetString("Share_Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link copied to clipboard.
        /// </summary>
        public static string Share_SharedMessage {
            get {
                return ResourceManager.GetString("Share_SharedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to open link.
        /// </summary>
        public static string Share_SharedMessageAlternative {
            get {
                return ResourceManager.GetString("Share_SharedMessageAlternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name: [b]{0}[/b]
        ///Entry name: [b]{1}[/b]
        ///Entry type: [b]{2}[/b].
        /// </summary>
        public static string Share_VerifyMessage {
            get {
                return ResourceManager.GetString("Share_VerifyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Everything OK?.
        /// </summary>
        public static string Share_VerifyMessageHeader {
            get {
                return ResourceManager.GetString("Share_VerifyMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nordschleife.
        /// </summary>
        public static string Theme_Nordschleife {
            get {
                return ResourceManager.GetString("Theme_Nordschleife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t play video.
        /// </summary>
        public static string Video_CannotPlay {
            get {
                return ResourceManager.GetString("Video_CannotPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, go to the Settings and enable VLC addon..
        /// </summary>
        public static string Video_CannotPlay_Commentary {
            get {
                return ResourceManager.GetString("Video_CannotPlay_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webpage says.
        /// </summary>
        public static string WebBrowser_Prompt {
            get {
                return ResourceManager.GetString("WebBrowser_Prompt", resourceCulture);
            }
        }
    }
}
