//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BinaryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BinaryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcManager.Properties.BinaryResources", typeof(BinaryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AssistsGamer {
            get {
                object obj = ResourceManager.GetObject("AssistsGamer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AssistsIntermediate {
            get {
                object obj = ResourceManager.GetObject("AssistsIntermediate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AssistsPro {
            get {
                object obj = ResourceManager.GetObject("AssistsPro", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PpFilterAtPreviewsSpecial {
            get {
                object obj = ResourceManager.GetObject("PpFilterAtPreviewsSpecial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PresetCmPreviewsGt5Like {
            get {
                object obj = ResourceManager.GetObject("PresetCmPreviewsGt5Like", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PresetCmPreviewsKunos {
            get {
                object obj = ResourceManager.GetObject("PresetCmPreviewsKunos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PresetCmPreviewsLight {
            get {
                object obj = ResourceManager.GetObject("PresetCmPreviewsLight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PresetPreviewsKunos {
            get {
                object obj = ResourceManager.GetObject("PresetPreviewsKunos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///  background: #000 !important;
        ///}
        ///
        ///body, #cntdwn, .driver_profile {
        ///  color: #FFF !important;
        ///}
        ///
        ///* {
        ///  font-family: Segoe UI, sans-serif !important;
        ///}
        ///
        ///a {
        ///  color: #E20035 !important;
        ///}
        ///
        ///#page {
        ///  background: #333 !important;
        ///}
        ///
        ///h1, h2 {
        ///  font-weight: 100 !important;
        ///  font-family: Segoe UI Light, Segoe UI, sans-serif !important;
        ///}
        ///
        ///.margin_top_0 {
        ///  margin-top: 20px !important;
        ///}
        ///
        ///.dd {
        ///  font-size: 12px;
        ///}
        ///
        ///#track_msdd, #car_msdd {
        ///  width: 300px !important;
        ///}
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RsrStyle {
            get {
                return ResourceManager.GetString("RsrStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ShowroomPanoramaTemplate {
            get {
                object obj = ResourceManager.GetObject("ShowroomPanoramaTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ShowroomPreviewSphere {
            get {
                object obj = ResourceManager.GetObject("ShowroomPreviewSphere", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #content &gt; div &gt; div + div, .header .logo, .header .mainmenu, .newmenucenter, .menu.bottom_links, #footer .lower, .newmenu + .__wrapper, div[id^=Box_jbeeb_], .myannouncement, #shoutbox .head {
        ///  display: none!important
        ///}
        ///#shoutbox {
        ///	margin-bottom: 0!important;
        ///  background: #333!important;
        ///}
        ///#shoutbox .panel { border-top: none !important; }
        ///#shoutbox input.text {
        ///	background: #111;
        ///  color: inherit;
        ///  font-family: inherit;
        ///  box-shadow: none !important;
        ///}
        ///#shoutbox .body { display: block !imp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SrsStyle {
            get {
                return ResourceManager.GetString("SrsStyle", resourceCulture);
            }
        }
    }
}
