//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcManager.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Updated.
        /// </summary>
        public static string App_ContentUpdated {
            get {
                return ResourceManager.GetString("App_ContentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version: {0}.
        /// </summary>
        public static string App_ContentUpdated_Details {
            get {
                return ResourceManager.GetString("App_ContentUpdated_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Version.
        /// </summary>
        public static string App_NewVersion {
            get {
                return ResourceManager.GetString("App_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update is ready: {0}.
        /// </summary>
        public static string App_NewVersion_Details {
            get {
                return ResourceManager.GetString("App_NewVersion_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t install additional content.
        /// </summary>
        public static string Arguments_CannotInstallAdditionalContent {
            get {
                return ResourceManager.GetString("Arguments_CannotInstallAdditionalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t install car’s setup.
        /// </summary>
        public static string Arguments_CannotInstallCarSetup {
            get {
                return ResourceManager.GetString("Arguments_CannotInstallCarSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t install setup.
        /// </summary>
        public static string Arguments_CannotInstallSetup {
            get {
                return ResourceManager.GetString("Arguments_CannotInstallSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSR has changed..
        /// </summary>
        public static string Arguments_CannotInstallSetup_Commentary {
            get {
                return ResourceManager.GetString("Arguments_CannotInstallSetup_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSR returned file in unsupported format..
        /// </summary>
        public static string Arguments_CannotInstallSetup_CommentaryFormat {
            get {
                return ResourceManager.GetString("Arguments_CannotInstallSetup_CommentaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t parse request.
        /// </summary>
        public static string Arguments_CannotParseRequest {
            get {
                return ResourceManager.GetString("Arguments_CannotParseRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure format is valid.
        /// </summary>
        public static string Arguments_CannotParseRequest_Commentary {
            get {
                return ResourceManager.GetString("Arguments_CannotParseRequest_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t process request.
        /// </summary>
        public static string Arguments_CannotProcessRequest {
            get {
                return ResourceManager.GetString("Arguments_CannotProcessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure data is valid..
        /// </summary>
        public static string Arguments_CannotProcessRequest_Commentary {
            get {
                return ResourceManager.GetString("Arguments_CannotProcessRequest_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t start race.
        /// </summary>
        public static string Arguments_CannotStartRace {
            get {
                return ResourceManager.GetString("Arguments_CannotStartRace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure required car &amp; track are installed and available..
        /// </summary>
        public static string Arguments_CannotStartRace_Commentary {
            get {
                return ResourceManager.GetString("Arguments_CannotStartRace_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata is missing..
        /// </summary>
        public static string Arguments_MetadataIsMissing {
            get {
                return ResourceManager.GetString("Arguments_MetadataIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as Generic.
        /// </summary>
        public static string Arguments_SaveAsGeneric {
            get {
                return ResourceManager.GetString("Arguments_SaveAsGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Arguments_Shared_Apply {
            get {
                return ResourceManager.GetString("Arguments_Shared_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply &amp; Save.
        /// </summary>
        public static string Arguments_Shared_ApplyAndSave {
            get {
                return ResourceManager.GetString("Arguments_Shared_ApplyAndSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply FFB Only.
        /// </summary>
        public static string Arguments_Shared_ApplyFfbOnly {
            get {
                return ResourceManager.GetString("Arguments_Shared_ApplyFfbOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Only.
        /// </summary>
        public static string Arguments_Shared_ApplyOnly {
            get {
                return ResourceManager.GetString("Arguments_Shared_ApplyOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just Go.
        /// </summary>
        public static string Arguments_Shared_JustGo {
            get {
                return ResourceManager.GetString("Arguments_Shared_JustGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Arguments_Shared_Save {
            get {
                return ResourceManager.GetString("Arguments_Shared_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Apply.
        /// </summary>
        public static string Arguments_Shared_SaveAndApply {
            get {
                return ResourceManager.GetString("Arguments_Shared_SaveAndApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Only.
        /// </summary>
        public static string Arguments_Shared_SaveOnly {
            get {
                return ResourceManager.GetString("Arguments_Shared_SaveOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to apply this preset?.
        /// </summary>
        public static string Arguments_Shared_ShouldApply {
            get {
                return ResourceManager.GetString("Arguments_Shared_ShouldApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to apply this preset or to save it for later?.
        /// </summary>
        public static string Arguments_Shared_ShouldApplyOrSave {
            get {
                return ResourceManager.GetString("Arguments_Shared_ShouldApplyOrSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: [b]{0}[/b]
        ///{1}: [b]{2}[/b]
        ///Author: [b]{3}[/b].
        /// </summary>
        public static string Arguments_SharedMessage {
            get {
                return ResourceManager.GetString("Arguments_SharedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [/b][i]?[/i][b].
        /// </summary>
        public static string Arguments_SharedMessage_EmptyValue {
            get {
                return ResourceManager.GetString("Arguments_SharedMessage_EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For.
        /// </summary>
        public static string Arguments_SharedMessage_For {
            get {
                return ResourceManager.GetString("Arguments_SharedMessage_For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Arguments_SharedMessage_Id {
            get {
                return ResourceManager.GetString("Arguments_SharedMessage_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported yet type: “{0}”.
        /// </summary>
        public static string Arguments_SharedUnsupported {
            get {
                return ResourceManager.GetString("Arguments_SharedUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Common_Change {
            get {
                return ResourceManager.GetString("Common_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer mode.
        /// </summary>
        public static string Common_DevMode {
            get {
                return ResourceManager.GetString("Common_DevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2} ms.
        /// </summary>
        public static string Common_MillisecondsFormat {
            get {
                return ResourceManager.GetString("Common_MillisecondsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brand Name.
        /// </summary>
        public static string Common_NewBrandName {
            get {
                return ResourceManager.GetString("Common_NewBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Name.
        /// </summary>
        public static string Common_NewName {
            get {
                return ResourceManager.GetString("Common_NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Common_Restart {
            get {
                return ResourceManager.GetString("Common_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string Main_About {
            get {
                return ResourceManager.GetString("Main_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t process argument.
        /// </summary>
        public static string Main_CannotProcessArgument {
            get {
                return ResourceManager.GetString("Main_CannotProcessArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure it’s in valid format..
        /// </summary>
        public static string Main_CannotProcessArgument_Commentary {
            get {
                return ResourceManager.GetString("Main_CannotProcessArgument_Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content.
        /// </summary>
        public static string Main_Content {
            get {
                return ResourceManager.GetString("Main_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drive.
        /// </summary>
        public static string Main_Drive {
            get {
                return ResourceManager.GetString("Main_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cars.
        /// </summary>
        public static string Main_Group_Cars {
            get {
                return ResourceManager.GetString("Main_Group_Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lan.
        /// </summary>
        public static string Main_Group_Lan {
            get {
                return ResourceManager.GetString("Main_Group_Lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live.
        /// </summary>
        public static string Main_Group_Live {
            get {
                return ResourceManager.GetString("Main_Group_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to miscellaneous.
        /// </summary>
        public static string Main_Group_Miscellaneous {
            get {
                return ResourceManager.GetString("Main_Group_Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online.
        /// </summary>
        public static string Main_Group_Online {
            get {
                return ResourceManager.GetString("Main_Group_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replays.
        /// </summary>
        public static string Main_Group_Replays {
            get {
                return ResourceManager.GetString("Main_Group_Replays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to screenshots.
        /// </summary>
        public static string Main_Group_Screenshots {
            get {
                return ResourceManager.GetString("Main_Group_Screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to presets.
        /// </summary>
        public static string Main_Group_ServerPresets {
            get {
                return ResourceManager.GetString("Main_Group_ServerPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to runned.
        /// </summary>
        public static string Main_Group_ServerRunned {
            get {
                return ResourceManager.GetString("Main_Group_ServerRunned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to showrooms.
        /// </summary>
        public static string Main_Group_Showrooms {
            get {
                return ResourceManager.GetString("Main_Group_Showrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to single.
        /// </summary>
        public static string Main_Group_Single {
            get {
                return ResourceManager.GetString("Main_Group_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracks.
        /// </summary>
        public static string Main_Group_Tracks {
            get {
                return ResourceManager.GetString("Main_Group_Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Main_Link_About {
            get {
                return ResourceManager.GetString("Main_Link_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string Main_Link_Apps {
            get {
                return ResourceManager.GetString("Main_Link_Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assetto Corsa.
        /// </summary>
        public static string Main_Link_AssettoCorsa {
            get {
                return ResourceManager.GetString("Main_Link_AssettoCorsa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string Main_Link_Career {
            get {
                return ResourceManager.GetString("Main_Link_Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenges.
        /// </summary>
        public static string Main_Link_Challenges {
            get {
                return ResourceManager.GetString("Main_Link_Challenges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Manager.
        /// </summary>
        public static string Main_Link_ContentManager {
            get {
                return ResourceManager.GetString("Main_Link_ContentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts.
        /// </summary>
        public static string Main_Link_Fonts {
            get {
                return ResourceManager.GetString("Main_Link_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Tips.
        /// </summary>
        public static string Main_Link_ImportantTips {
            get {
                return ResourceManager.GetString("Main_Link_ImportantTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PP Filters.
        /// </summary>
        public static string Main_Link_PpFilters {
            get {
                return ResourceManager.GetString("Main_Link_PpFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick.
        /// </summary>
        public static string Main_Link_QuickDrive {
            get {
                return ResourceManager.GetString("Main_Link_QuickDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        public static string Main_Link_ReleaseNotes {
            get {
                return ResourceManager.GetString("Main_Link_ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSR.
        /// </summary>
        public static string Main_Link_Rsr {
            get {
                return ResourceManager.GetString("Main_Link_Rsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRS.
        /// </summary>
        public static string Main_Link_Srs {
            get {
                return ResourceManager.GetString("Main_Link_Srs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string Main_Link_Weather {
            get {
                return ResourceManager.GetString("Main_Link_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to media.
        /// </summary>
        public static string Main_Media {
            get {
                return ResourceManager.GetString("Main_Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now With Official Support!.
        /// </summary>
        public static string Main_OfficialSupportNotification {
            get {
                return ResourceManager.GetString("Main_OfficialSupportNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New starter is ready, now without any patching at all.
        /// </summary>
        public static string Main_OfficialSupportNotification_Details {
            get {
                return ResourceManager.GetString("Main_OfficialSupportNotification_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since 1.7 Kunos added an official support for custom launchers. Basically, it works like Starter+, but now CM doesn&apos;t have to replace AssettoCorsa.exe, and it&apos;s great! Would you like to switch to a new Official Starter?.
        /// </summary>
        public static string Main_OfficialSupportNotification_Message {
            get {
                return ResourceManager.GetString("Main_OfficialSupportNotification_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server.
        /// </summary>
        public static string Main_Server {
            get {
                return ResourceManager.GetString("Main_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Main_Settings {
            get {
                return ResourceManager.GetString("Main_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Manager (Lite Mode).
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception:
        ///
        ///{0}.
        /// </summary>
        public static string Main_UnhandledException {
            get {
                return ResourceManager.GetString("Main_UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting information about the event….
        /// </summary>
        public static string RsrStarter_GettingInformation {
            get {
                return ResourceManager.GetString("RsrStarter_GettingInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appearance.
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color:.
        /// </summary>
        public static string Settings_Appearance_ColorLabel {
            get {
                return ResourceManager.GetString("Settings_Appearance_ColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic background.
        /// </summary>
        public static string Settings_Appearance_DynamicBackground {
            get {
                return ResourceManager.GetString("Settings_Appearance_DynamicBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart app to apply changes.
        /// </summary>
        public static string Settings_Appearance_ImageScaling_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Appearance_ImageScaling_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image scaling quality:.
        /// </summary>
        public static string Settings_Appearance_ImageScalingLabel {
            get {
                return ResourceManager.GetString("Settings_Appearance_ImageScalingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large search boxes.
        /// </summary>
        public static string Settings_Appearance_LargeSearchBoxes {
            get {
                return ResourceManager.GetString("Settings_Appearance_LargeSearchBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By the way, try shortcuts like F6/Ctrl+T/Ctrl+W/Ctrl+Tab/etc..
        /// </summary>
        public static string Settings_Appearance_LargeSearchBoxes_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Appearance_LargeSearchBoxes_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup toolbars.
        /// </summary>
        public static string Settings_Appearance_PopupToolbars {
            get {
                return ResourceManager.GetString("Settings_Appearance_PopupToolbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t forget, there is a keyboard shortcut for every button.
        /// </summary>
        public static string Settings_Appearance_PopupToolbars_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Appearance_PopupToolbars_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small font.
        /// </summary>
        public static string Settings_Appearance_SmallFont {
            get {
                return ResourceManager.GetString("Settings_Appearance_SmallFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text rendering:.
        /// </summary>
        public static string Settings_Appearance_TextRenderingLabel {
            get {
                return ResourceManager.GetString("Settings_Appearance_TextRenderingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string Settings_Appearance_ThemeLabel {
            get {
                return ResourceManager.GetString("Settings_Appearance_ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition animation:.
        /// </summary>
        public static string Settings_Appearance_TransitionAnimationLabel {
            get {
                return ResourceManager.GetString("Settings_Appearance_TransitionAnimationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content.
        /// </summary>
        public static string Settings_Content {
            get {
                return ResourceManager.GetString("Settings_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars:.
        /// </summary>
        public static string Settings_Content_CarsHeader {
            get {
                return ResourceManager.GetString("Settings_Content_CarsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change brand&apos;s icon automatically.
        /// </summary>
        public static string Settings_Content_ChangeBrandIcon {
            get {
                return ResourceManager.GetString("Settings_Content_ChangeBrandIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download previews of common showrooms.
        /// </summary>
        public static string Settings_Content_DownloadPreviews {
            get {
                return ResourceManager.GetString("Settings_Content_DownloadPreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I doubt you have time to update all of them.
        /// </summary>
        public static string Settings_Content_DownloadPreviews_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Content_DownloadPreviews_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font’s icon symbol:.
        /// </summary>
        public static string Settings_Content_FontIconSymbol {
            get {
                return ResourceManager.GetString("Settings_Content_FontIconSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One symbol which will be used for an icon.
        /// </summary>
        public static string Settings_Content_FontIconSymbol_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Content_FontIconSymbol_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonts:.
        /// </summary>
        public static string Settings_Content_FontsHeader {
            get {
                return ResourceManager.GetString("Settings_Content_FontsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information search:.
        /// </summary>
        public static string Settings_Content_InformationSearchHeader {
            get {
                return ResourceManager.GetString("Settings_Content_InformationSearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smaller value may increase UI responsibleness, but decrease loading times.
        /// </summary>
        public static string Settings_Content_LoadingConcurrency_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Content_LoadingConcurrency_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading concurrency:.
        /// </summary>
        public static string Settings_Content_LoadingConcurrencyLabel {
            get {
                return ResourceManager.GetString("Settings_Content_LoadingConcurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look at Wikipedia by default.
        /// </summary>
        public static string Settings_Content_LookAtWikipedia {
            get {
                return ResourceManager.GetString("Settings_Content_LookAtWikipedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add “site:wikipedia.org” by default.
        /// </summary>
        public static string Settings_Content_LookAtWikipedia_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Content_LookAtWikipedia_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as new:.
        /// </summary>
        public static string Settings_Content_MarkAsNewLabel {
            get {
                return ResourceManager.GetString("Settings_Content_MarkAsNewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically scroll to selected item.
        /// </summary>
        public static string Settings_Content_ScrollAutomatically {
            get {
                return ResourceManager.GetString("Settings_Content_ScrollAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example, on disabling.
        /// </summary>
        public static string Settings_Content_ScrollAutomatically_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Content_ScrollAutomatically_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search engine:.
        /// </summary>
        public static string Settings_Content_SearchEngine {
            get {
                return ResourceManager.GetString("Settings_Content_SearchEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showrooms:.
        /// </summary>
        public static string Settings_Content_ShowroomsHeader {
            get {
                return ResourceManager.GetString("Settings_Content_ShowroomsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom showroom.
        /// </summary>
        public static string Settings_CustomShowroom {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-adjusting camera pivot.
        /// </summary>
        public static string Settings_CustomShowroom_AutoAdjustPivot {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_AutoAdjustPivot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tries to keep a car at the center of the screen as much as possible (but without any heavy calculations).
        /// </summary>
        public static string Settings_CustomShowroom_AutoAdjustPivot_Tooltip {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_AutoAdjustPivot_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use bloom.
        /// </summary>
        public static string Settings_CustomShowroom_Bloom {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_Bloom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable if you need maximum performance.
        /// </summary>
        public static string Settings_CustomShowroom_Bloom_Tooltip {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_Bloom_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use by default:.
        /// </summary>
        public static string Settings_CustomShowroom_DefaultType {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_DefaultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold Ctrl when starting to select the other one.
        /// </summary>
        public static string Settings_CustomShowroom_DefaultType_Tooltip {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_DefaultType_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fancy Showroom:.
        /// </summary>
        public static string Settings_CustomShowroom_FancyHeader {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_FancyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FXAA.
        /// </summary>
        public static string Settings_CustomShowroom_Fxaa {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_Fxaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can toggle it any time by pressing F.
        /// </summary>
        public static string Settings_CustomShowroom_Fxaa_Tooltip {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_Fxaa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert mouse buttons.
        /// </summary>
        public static string Settings_CustomShowroom_InvertMouseButtons {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_InvertMouseButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use left mouse button for panning and right for rotating a model instead.
        /// </summary>
        public static string Settings_CustomShowroom_InvertMouseButtons_Tooltip {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_InvertMouseButtons_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lite Showroom:.
        /// </summary>
        public static string Settings_CustomShowroom_LiteHeader {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_LiteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use MSAA.
        /// </summary>
        public static string Settings_CustomShowroom_Msaa {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_Msaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes picture even worse if you asked me.
        /// </summary>
        public static string Settings_CustomShowroom_Msaa_Tooltip {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_Msaa_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default showroom:.
        /// </summary>
        public static string Settings_CustomShowroom_Showroom {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_Showroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lite Showroom is DirectX 10-compatible, much simpler and easier for a videocard. Perfect solution for skins drawing..
        /// </summary>
        public static string Settings_CustomShowroom_TypeComment {
            get {
                return ResourceManager.GetString("Settings_CustomShowroom_TypeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dev.
        /// </summary>
        public static string Settings_Dev {
            get {
                return ResourceManager.GetString("Settings_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drive.
        /// </summary>
        public static string Settings_Drive {
            get {
                return ResourceManager.GetString("Settings_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 32-bit version.
        /// </summary>
        public static string Settings_Drive_32bit {
            get {
                return ResourceManager.GetString("Settings_Drive_32bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to change AI level.
        /// </summary>
        public static string Settings_Drive_ChangeAiLevel {
            get {
                return ResourceManager.GetString("Settings_Drive_ChangeAiLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to change car’s skin.
        /// </summary>
        public static string Settings_Drive_ChangeCarSkin {
            get {
                return ResourceManager.GetString("Settings_Drive_ChangeCarSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically convert screenshots from BMP-format to JPEG on exit.
        /// </summary>
        public static string Settings_Drive_ConvertScreenshots {
            get {
                return ResourceManager.GetString("Settings_Drive_ConvertScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I highly recommend to enable Magick.NET first — with it, result quality will be higher.
        /// </summary>
        public static string Settings_Drive_ConvertScreenshots_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Drive_ConvertScreenshots_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace clouds by weather’s clouds if exist.
        /// </summary>
        public static string Settings_Drive_CustomClouds {
            get {
                return ResourceManager.GetString("Settings_Drive_CustomClouds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of course, only temporary.
        /// </summary>
        public static string Settings_Drive_CustomClouds_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Drive_CustomClouds_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game-related events:.
        /// </summary>
        public static string Settings_Drive_EventsHeader {
            get {
                return ResourceManager.GetString("Settings_Drive_EventsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand bounds.
        /// </summary>
        public static string Settings_Drive_ExpandBounds {
            get {
                return ResourceManager.GetString("Settings_Drive_ExpandBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to set up to 999 laps and stuff, use on your own risk..
        /// </summary>
        public static string Settings_Drive_ExpandBounds_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Drive_ExpandBounds_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kunos career:.
        /// </summary>
        public static string Settings_Drive_KunosCareerHeader {
            get {
                return ResourceManager.GetString("Settings_Drive_KunosCareerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Settings_Drive_NameLabel {
            get {
                return ResourceManager.GetString("Settings_Drive_NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality:.
        /// </summary>
        public static string Settings_Drive_NationalityLabel {
            get {
                return ResourceManager.GetString("Settings_Drive_NationalityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use different name online.
        /// </summary>
        public static string Settings_Drive_OnlineName_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Drive_OnlineName_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online name:.
        /// </summary>
        public static string Settings_Drive_OnlineNameLabel {
            get {
                return ResourceManager.GetString("Settings_Drive_OnlineNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player’s name:.
        /// </summary>
        public static string Settings_Drive_PlayerNameHeader {
            get {
                return ResourceManager.GetString("Settings_Drive_PlayerNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command will be executed after acs.exe finished, but before reading all result json-files.
        ///[br]
        ///[br]Values for replacement:
        ///[br] [b][mono]{type}[/mono][/b] — type of race;
        ///[br] [b][mono]{car}[/mono][/b] — car&apos;s name;
        ///[br] [b][mono]{car.id}[/mono][/b] — car&apos;s id;
        ///[br] [b][mono]{track}[/mono][/b] — track&apos;s name;
        ///[br] [b][mono]{track.id}[/mono][/b] — track&apos;s id.
        ///[br]
        ///[br]If you need some other values, please, contact us and we&apos;ll add them.
        ///[br]
        ///[br]Working directory will be set to Assetto Corsa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Settings_Drive_PostCommand_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Drive_PostCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-race event command:.
        /// </summary>
        public static string Settings_Drive_PostCommandLabel {
            get {
                return ResourceManager.GetString("Settings_Drive_PostCommandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command will be executed before starting acs.exe, but after setting all ini-files.
        ///[br]
        ///[br]Values for replacement:
        ///[br] [b][mono]{type}[/mono][/b] — type of race;
        ///[br] [b][mono]{car}[/mono][/b] — car&apos;s name;
        ///[br] [b][mono]{car.id}[/mono][/b] — car&apos;s id;
        ///[br] [b][mono]{track}[/mono][/b] — track&apos;s name;
        ///[br] [b][mono]{track.id}[/mono][/b] — track&apos;s id.
        ///[br]
        ///[br]If you need some other values, please, contact us and we&apos;ll add them.
        ///[br]
        ///[br]Working directory will be set to Assetto Corsa folder  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Settings_Drive_PreCommand_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Drive_PreCommand_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-race event command:.
        /// </summary>
        public static string Settings_Drive_PreCommandLabel {
            get {
                return ResourceManager.GetString("Settings_Drive_PreCommandLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Drive:.
        /// </summary>
        public static string Settings_Drive_QuickDriveHeader {
            get {
                return ResourceManager.GetString("Settings_Drive_QuickDriveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show results of Practice session.
        /// </summary>
        public static string Settings_Drive_SkipPracticeResults {
            get {
                return ResourceManager.GetString("Settings_Drive_SkipPracticeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game starter.
        /// </summary>
        public static string Settings_Drive_Starter {
            get {
                return ResourceManager.GetString("Settings_Drive_Starter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start race immediately.
        /// </summary>
        public static string Settings_Drive_StartImmediately {
            get {
                return ResourceManager.GetString("Settings_Drive_StartImmediately", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assetto Corsa folder:.
        /// </summary>
        public static string Settings_General_AcFolderLabel {
            get {
                return ResourceManager.GetString("Settings_General_AcFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App:.
        /// </summary>
        public static string Settings_General_AppHeader {
            get {
                return ResourceManager.GetString("Settings_General_AppHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App key:.
        /// </summary>
        public static string Settings_General_AppKeyLabel {
            get {
                return ResourceManager.GetString("Settings_General_AppKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App version:.
        /// </summary>
        public static string Settings_General_AppVersionLabel {
            get {
                return ResourceManager.GetString("Settings_General_AppVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Updates:.
        /// </summary>
        public static string Settings_General_AutoUpdatesHeader {
            get {
                return ResourceManager.GetString("Settings_General_AutoUpdatesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change path to AC root folder.
        /// </summary>
        public static string Settings_General_ChangeAcRoot {
            get {
                return ResourceManager.GetString("Settings_General_ChangeAcRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change path? App will be restarted..
        /// </summary>
        public static string Settings_General_ChangeAcRoot_Message {
            get {
                return ResourceManager.GetString("Settings_General_ChangeAcRoot_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string Settings_General_CheckForUpdates {
            get {
                return ResourceManager.GetString("Settings_General_CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates:.
        /// </summary>
        public static string Settings_General_CheckForUpdatesLabel {
            get {
                return ResourceManager.GetString("Settings_General_CheckForUpdatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content version:.
        /// </summary>
        public static string Settings_General_ContentVersionLabel {
            get {
                return ResourceManager.GetString("Settings_General_ContentVersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update to non-tested versions.
        /// </summary>
        public static string Settings_General_TestingAccess {
            get {
                return ResourceManager.GetString("Settings_General_TestingAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Access:.
        /// </summary>
        public static string Settings_General_TestingAccessHeader {
            get {
                return ResourceManager.GetString("Settings_General_TestingAccessHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Up.
        /// </summary>
        public static string Settings_General_ValuesCleanUp {
            get {
                return ResourceManager.GetString("Settings_General_ValuesCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all nonimportant values.
        /// </summary>
        public static string Settings_General_ValuesCleanUp_Tooltip {
            get {
                return ResourceManager.GetString("Settings_General_ValuesCleanUp_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values Storage:.
        /// </summary>
        public static string Settings_General_ValuesHeader {
            get {
                return ResourceManager.GetString("Settings_General_ValuesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} entry.
        /// </summary>
        public static string Settings_General_ValuesNumber {
            get {
                return ResourceManager.GetString("Settings_General_ValuesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving time:.
        /// </summary>
        public static string Settings_General_ValuesSavingTimeLabel {
            get {
                return ResourceManager.GetString("Settings_General_ValuesSavingTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size:.
        /// </summary>
        public static string Settings_General_ValuesSizeLabel {
            get {
                return ResourceManager.GetString("Settings_General_ValuesSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Menu shortcut (for modern notifications).
        /// </summary>
        public static string Settings_General_WindowsShortcut {
            get {
                return ResourceManager.GetString("Settings_General_WindowsShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Start Menu shortcut if it’s missing; required for showing proper notifications in Windows 8 and 10.
        /// </summary>
        public static string Settings_General_WindowsShortcut_Tooltip {
            get {
                return ResourceManager.GetString("Settings_General_WindowsShortcut_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live.
        /// </summary>
        public static string Settings_Live {
            get {
                return ResourceManager.GetString("Settings_Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom style.
        /// </summary>
        public static string Settings_Live_CustomStyle {
            get {
                return ResourceManager.GetString("Settings_Live_CustomStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable RSR Live Timing tab.
        /// </summary>
        public static string Settings_Live_EnableRsr {
            get {
                return ResourceManager.GetString("Settings_Live_EnableRsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Sim Racing System (SRS) tab.
        /// </summary>
        public static string Settings_Live_EnableSrs {
            get {
                return ResourceManager.GetString("Settings_Live_EnableSrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically toggle RSR app.
        /// </summary>
        public static string Settings_Live_RsrAutoToggleApp {
            get {
                return ResourceManager.GetString("Settings_Live_RsrAutoToggleApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically show or hide RSR app if starting race isn’t RSR-related.
        /// </summary>
        public static string Settings_Live_RsrAutoToggleApp_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Live_RsrAutoToggleApp_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom optimized style for built-in RSR website.
        /// </summary>
        public static string Settings_Live_RsrCustomStyle_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Live_RsrCustomStyle_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use different name when RSR form is enabled.
        /// </summary>
        public static string Settings_Live_RsrName_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Live_RsrName_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSR name:.
        /// </summary>
        public static string Settings_Live_RsrNameLabel {
            get {
                return ResourceManager.GetString("Settings_Live_RsrNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom optimized style for built-in SRS website.
        /// </summary>
        public static string Settings_Live_SrsCustomStyle_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Live_SrsCustomStyle_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining from Online.
        /// </summary>
        public static string Settings_Live_SrsJoinFromOnline {
            get {
                return ResourceManager.GetString("Settings_Live_SrsJoinFromOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App will set a special SRS name automatically to avoid problems.
        /// </summary>
        public static string Settings_Live_SrsJoinFromOnline_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Live_SrsJoinFromOnline_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default value: “SimRacingSystem*”.
        /// </summary>
        public static string Settings_Live_SrsOnlineMask_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Live_SrsOnlineMask_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mask for SRS servers:.
        /// </summary>
        public static string Settings_Live_SrsOnlineMaskLabel {
            get {
                return ResourceManager.GetString("Settings_Live_SrsOnlineMaskLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to online.
        /// </summary>
        public static string Settings_Online {
            get {
                return ResourceManager.GetString("Settings_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding by IP:.
        /// </summary>
        public static string Settings_Online_AddingByIpHeader {
            get {
                return ResourceManager.GetString("Settings_Online_AddingByIpHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan timeout.
        /// </summary>
        public static string Settings_Online_AddingByIpScanTimeout {
            get {
                return ResourceManager.GetString("Settings_Online_AddingByIpScanTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact UI.
        /// </summary>
        public static string Settings_Online_CompactUi {
            get {
                return ResourceManager.GetString("Settings_Online_CompactUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection:.
        /// </summary>
        public static string Settings_Online_ConnectionHeader {
            get {
                return ResourceManager.GetString("Settings_Online_ConnectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAN:.
        /// </summary>
        public static string Settings_Online_LanHeader {
            get {
                return ResourceManager.GetString("Settings_Online_LanHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan using connections:.
        /// </summary>
        public static string Settings_Online_LanScanConnectionLabel {
            get {
                return ResourceManager.GetString("Settings_Online_LanScanConnectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load server information directly.
        /// </summary>
        public static string Settings_Online_LoadInformationDirectly {
            get {
                return ResourceManager.GetString("Settings_Online_LoadInformationDirectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load server information directly instead of using AC servers; could be faster and more actual, but some information (such as active session) will be missing.
        /// </summary>
        public static string Settings_Online_LoadInformationDirectly_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Online_LoadInformationDirectly_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping concurrency.
        /// </summary>
        public static string Settings_Online_PingConcurrency {
            get {
                return ResourceManager.GetString("Settings_Online_PingConcurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase value to make pinging of the whole list go faster, but it’ll be less accurate.
        /// </summary>
        public static string Settings_Online_PingConcurrency_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Online_PingConcurrency_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinging:.
        /// </summary>
        public static string Settings_Online_PingingHeader {
            get {
                return ResourceManager.GetString("Settings_Online_PingingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping timeout.
        /// </summary>
        public static string Settings_Online_PingTimeout {
            get {
                return ResourceManager.GetString("Settings_Online_PingTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use threads instead of asynchronous API.
        /// </summary>
        public static string Settings_Online_PingWithThreads {
            get {
                return ResourceManager.GetString("Settings_Online_PingWithThreads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most correct pinging, but the slowest one.
        /// </summary>
        public static string Settings_Online_PingWithThreads_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Online_PingWithThreads_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some enumeration like “9000-10000”.
        /// </summary>
        public static string Settings_Online_PortsByIp_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Online_PortsByIp_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan ports:.
        /// </summary>
        public static string Settings_Online_PortsLabel {
            get {
                return ResourceManager.GetString("Settings_Online_PortsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some enumeration like “9600,9602,9700-9750”.
        /// </summary>
        public static string Settings_Online_PortsLan_Tooltip {
            get {
                return ResourceManager.GetString("Settings_Online_PortsLan_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember passwords.
        /// </summary>
        public static string Settings_Online_RememberPasswords {
            get {
                return ResourceManager.GetString("Settings_Online_RememberPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server:.
        /// </summary>
        public static string Settings_Online_ServerLabel {
            get {
                return ResourceManager.GetString("Settings_Online_ServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Settings_Online_ServerPresetsManagerEnable {
            get {
                return ResourceManager.GetString("Settings_Online_ServerPresetsManagerEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server presets manager:.
        /// </summary>
        public static string Settings_Online_ServerPresetsManagerHeader {
            get {
                return ResourceManager.GetString("Settings_Online_ServerPresetsManagerHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to plugins.
        /// </summary>
        public static string Settings_Plugins {
            get {
                return ResourceManager.GetString("Settings_Plugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quick switches.
        /// </summary>
        public static string Settings_QuickSwitches {
            get {
                return ResourceManager.GetString("Settings_QuickSwitches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replays.
        /// </summary>
        public static string Settings_Replays {
            get {
                return ResourceManager.GetString("Settings_Replays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sharing.
        /// </summary>
        public static string Settings_Sharing {
            get {
                return ResourceManager.GetString("Settings_Sharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can’t restore damaged JSON.
        /// </summary>
        public static string Solution_CannotRestoreJsonFile {
            get {
                return ResourceManager.GetString("Solution_CannotRestoreJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change brand’s badge.
        /// </summary>
        public static string Solution_ChangeBrandBadge {
            get {
                return ResourceManager.GetString("Solution_ChangeBrandBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new brand’s badge from the list.
        /// </summary>
        public static string Solution_ChangeBrandBadge_Details {
            get {
                return ResourceManager.GetString("Solution_ChangeBrandBadge_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change parent.
        /// </summary>
        public static string Solution_ChangeParent {
            get {
                return ResourceManager.GetString("Solution_ChangeParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new parent from cars list.
        /// </summary>
        public static string Solution_ChangeParent_Details {
            get {
                return ResourceManager.GetString("Solution_ChangeParent_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change upgrade icon.
        /// </summary>
        public static string Solution_ChangeUpgradeIcon {
            get {
                return ResourceManager.GetString("Solution_ChangeUpgradeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or create a new upgrade icon with the editor.
        /// </summary>
        public static string Solution_ChangeUpgradeIcon_Details {
            get {
                return ResourceManager.GetString("Solution_ChangeUpgradeIcon_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create empty skin.
        /// </summary>
        public static string Solution_CreateEmptySkin {
            get {
                return ResourceManager.GetString("Solution_CreateEmptySkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new empty skin called “default”.
        /// </summary>
        public static string Solution_CreateEmptySkin_Details {
            get {
                return ResourceManager.GetString("Solution_CreateEmptySkin_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        public static string Solution_Enable {
            get {
                return ResourceManager.GetString("Solution_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move font from “fonts-off” to “fonts”.
        /// </summary>
        public static string Solution_Enable_Details {
            get {
                return ResourceManager.GetString("Solution_Enable_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable {0}.
        /// </summary>
        public static string Solution_EnableSkin {
            get {
                return ResourceManager.GetString("Solution_EnableSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable disabled skin.
        /// </summary>
        public static string Solution_EnableSkin_Details {
            get {
                return ResourceManager.GetString("Solution_EnableSkin_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find track.
        /// </summary>
        public static string Solution_FindTrack {
            get {
                return ResourceManager.GetString("Solution_FindTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to find track online.
        /// </summary>
        public static string Solution_FindTrack_Details {
            get {
                return ResourceManager.GetString("Solution_FindTrack_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix name.
        /// </summary>
        public static string Solution_FixName {
            get {
                return ResourceManager.GetString("Solution_FixName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove invalid symbols.
        /// </summary>
        public static string Solution_FixName_Details {
            get {
                return ResourceManager.GetString("Solution_FixName_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new livery.
        /// </summary>
        public static string Solution_GenerateLivery {
            get {
                return ResourceManager.GetString("Solution_GenerateLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a new livery using last settings of Livery Editor.
        /// </summary>
        public static string Solution_GenerateLivery_Details {
            get {
                return ResourceManager.GetString("Solution_GenerateLivery_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new file.
        /// </summary>
        public static string Solution_GenerateNew {
            get {
                return ResourceManager.GetString("Solution_GenerateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New empty file will be created; don’t forget to set proper values and save it afterwards.
        /// </summary>
        public static string Solution_GenerateNew_Details {
            get {
                return ResourceManager.GetString("Solution_GenerateNew_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate new preview.
        /// </summary>
        public static string Solution_GeneratePreview {
            get {
                return ResourceManager.GetString("Solution_GeneratePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a new preview using recently used preset.
        /// </summary>
        public static string Solution_GeneratePreview_Details {
            get {
                return ResourceManager.GetString("Solution_GeneratePreview_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an empty model.
        /// </summary>
        public static string Solution_MakeEmptyModel {
            get {
                return ResourceManager.GetString("Solution_MakeEmptyModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With nothing, only emptyness.
        /// </summary>
        public static string Solution_MakeEmptyModel_Details {
            get {
                return ResourceManager.GetString("Solution_MakeEmptyModel_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make generic.
        /// </summary>
        public static string Solution_MakeGeneric {
            get {
                return ResourceManager.GetString("Solution_MakeGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to generic folder.
        /// </summary>
        public static string Solution_MakeGeneric_Details {
            get {
                return ResourceManager.GetString("Solution_MakeGeneric_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make independent.
        /// </summary>
        public static string Solution_MakeIndependent {
            get {
                return ResourceManager.GetString("Solution_MakeIndependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove id of missing parent from ui_car.json.
        /// </summary>
        public static string Solution_MakeIndependent_Details {
            get {
                return ResourceManager.GetString("Solution_MakeIndependent_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate random livery.
        /// </summary>
        public static string Solution_RandomLivery {
            get {
                return ResourceManager.GetString("Solution_RandomLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate a new livery using random settings.
        /// </summary>
        public static string Solution_RandomLivery_Details {
            get {
                return ResourceManager.GetString("Solution_RandomLivery_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove object.
        /// </summary>
        public static string Solution_RemoveObject {
            get {
                return ResourceManager.GetString("Solution_RemoveObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object will be removed to the Recycle Bin.
        /// </summary>
        public static string Solution_RemoveObject_Details {
            get {
                return ResourceManager.GetString("Solution_RemoveObject_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove replay.
        /// </summary>
        public static string Solution_RemoveReplay {
            get {
                return ResourceManager.GetString("Solution_RemoveReplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay will be removed to the Recycle Bin.
        /// </summary>
        public static string Solution_RemoveReplay_Details {
            get {
                return ResourceManager.GetString("Solution_RemoveReplay_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to restore JSON file.
        /// </summary>
        public static string Solution_RestoreJsonFile {
            get {
                return ResourceManager.GetString("Solution_RestoreJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App will make an attempt to read known properties from damaged JSON file (be carefull, data loss is possible).
        /// </summary>
        public static string Solution_RestoreJsonFile_Details {
            get {
                return ResourceManager.GetString("Solution_RestoreJsonFile_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set {0} badge.
        /// </summary>
        public static string Solution_SetBrandBadge {
            get {
                return ResourceManager.GetString("Solution_SetBrandBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the brand’s badge from Content storage.
        /// </summary>
        public static string Solution_SetBrandBadge_Details {
            get {
                return ResourceManager.GetString("Solution_SetBrandBadge_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set brand name.
        /// </summary>
        public static string Solution_SetBrandName {
            get {
                return ResourceManager.GetString("Solution_SetBrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just set a new brand name.
        /// </summary>
        public static string Solution_SetBrandName_Details {
            get {
                return ResourceManager.GetString("Solution_SetBrandName_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new brand name:.
        /// </summary>
        public static string Solution_SetBrandName_Prompt {
            get {
                return ResourceManager.GetString("Solution_SetBrandName_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set brand name based on car’s name.
        /// </summary>
        public static string Solution_SetBrandNameFromName {
            get {
                return ResourceManager.GetString("Solution_SetBrandNameFromName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New brand name will be: “{0}”.
        /// </summary>
        public static string Solution_SetBrandNameFromName_Details {
            get {
                return ResourceManager.GetString("Solution_SetBrandNameFromName_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set name.
        /// </summary>
        public static string Solution_SetName {
            get {
                return ResourceManager.GetString("Solution_SetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just set a new name.
        /// </summary>
        public static string Solution_SetName_Details {
            get {
                return ResourceManager.GetString("Solution_SetName_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new name:.
        /// </summary>
        public static string Solution_SetName_Prompt {
            get {
                return ResourceManager.GetString("Solution_SetName_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set name based on ID.
        /// </summary>
        public static string Solution_SetNameFromId {
            get {
                return ResourceManager.GetString("Solution_SetNameFromId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name will be: “{0}”.
        /// </summary>
        public static string Solution_SetNameFromId_Details {
            get {
                return ResourceManager.GetString("Solution_SetNameFromId_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set “{0}” icon.
        /// </summary>
        public static string Solution_SetUpgradeIcon {
            get {
                return ResourceManager.GetString("Solution_SetUpgradeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the upgrade icon from Content storage.
        /// </summary>
        public static string Solution_SetUpgradeIcon_Details {
            get {
                return ResourceManager.GetString("Solution_SetUpgradeIcon_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup new livery.
        /// </summary>
        public static string Solution_SetupLivery {
            get {
                return ResourceManager.GetString("Solution_SetupLivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new livery using Livery Editor.
        /// </summary>
        public static string Solution_SetupLivery_Details {
            get {
                return ResourceManager.GetString("Solution_SetupLivery_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup and generate new preview.
        /// </summary>
        public static string Solution_SetupPreview {
            get {
                return ResourceManager.GetString("Solution_SetupPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new preview through settings.
        /// </summary>
        public static string Solution_SetupPreview_Details {
            get {
                return ResourceManager.GetString("Solution_SetupPreview_Details", resourceCulture);
            }
        }
    }
}
