//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstFloor.ModernUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FirstFloor.ModernUI.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BrokenImage {
            get {
                object obj = ResourceManager.GetObject("BrokenImage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FiltersLinkAll {
            get {
                return ResourceManager.GetString("FiltersLinkAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Password.
        /// </summary>
        public static string HidePassword {
            get {
                return ResourceManager.GetString("HidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Files|*.jpg;*.jpeg;*.png;*.gif;*.tif|All files (*.*)|*.*.
        /// </summary>
        public static string ImagesFilter {
            get {
                return ResourceManager.GetString("ImagesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string KeyAlt {
            get {
                return ResourceManager.GetString("KeyAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt (Left).
        /// </summary>
        public static string KeyAltLeft {
            get {
                return ResourceManager.GetString("KeyAltLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt (Right).
        /// </summary>
        public static string KeyAltRight {
            get {
                return ResourceManager.GetString("KeyAltRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backspace.
        /// </summary>
        public static string KeyBackspace {
            get {
                return ResourceManager.GetString("KeyBackspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Back.
        /// </summary>
        public static string KeyBrowserBack {
            get {
                return ResourceManager.GetString("KeyBrowserBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Favorites.
        /// </summary>
        public static string KeyBrowserFavorites {
            get {
                return ResourceManager.GetString("KeyBrowserFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Forward.
        /// </summary>
        public static string KeyBrowserForward {
            get {
                return ResourceManager.GetString("KeyBrowserForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Home.
        /// </summary>
        public static string KeyBrowserHome {
            get {
                return ResourceManager.GetString("KeyBrowserHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Refresh.
        /// </summary>
        public static string KeyBrowserRefresh {
            get {
                return ResourceManager.GetString("KeyBrowserRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Search.
        /// </summary>
        public static string KeyBrowserSearch {
            get {
                return ResourceManager.GetString("KeyBrowserSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Stop.
        /// </summary>
        public static string KeyBrowserStop {
            get {
                return ResourceManager.GetString("KeyBrowserStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock.
        /// </summary>
        public static string KeyCapsLock {
            get {
                return ResourceManager.GetString("KeyCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context Menu.
        /// </summary>
        public static string KeyContextMenu {
            get {
                return ResourceManager.GetString("KeyContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string KeyControl {
            get {
                return ResourceManager.GetString("KeyControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control (Left).
        /// </summary>
        public static string KeyControlLeft {
            get {
                return ResourceManager.GetString("KeyControlLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control (Right).
        /// </summary>
        public static string KeyControlRight {
            get {
                return ResourceManager.GetString("KeyControlRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string KeyDelete {
            get {
                return ResourceManager.GetString("KeyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down Arrow.
        /// </summary>
        public static string KeyDownArrow {
            get {
                return ResourceManager.GetString("KeyDownArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string KeyEnd {
            get {
                return ResourceManager.GetString("KeyEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string KeyEnter {
            get {
                return ResourceManager.GetString("KeyEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escape.
        /// </summary>
        public static string KeyEscape {
            get {
                return ResourceManager.GetString("KeyEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string KeyHelp {
            get {
                return ResourceManager.GetString("KeyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string KeyHome {
            get {
                return ResourceManager.GetString("KeyHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string KeyInsert {
            get {
                return ResourceManager.GetString("KeyInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Favorite Application 1.
        /// </summary>
        public static string KeyLaunchApplication1 {
            get {
                return ResourceManager.GetString("KeyLaunchApplication1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Favorite Application 2.
        /// </summary>
        public static string KeyLaunchApplication2 {
            get {
                return ResourceManager.GetString("KeyLaunchApplication2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Mail.
        /// </summary>
        public static string KeyLaunchMail {
            get {
                return ResourceManager.GetString("KeyLaunchMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Arrow.
        /// </summary>
        public static string KeyLeftArrow {
            get {
                return ResourceManager.GetString("KeyLeftArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Track.
        /// </summary>
        public static string KeyMediaNextTrack {
            get {
                return ResourceManager.GetString("KeyMediaNextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string KeyMediaPlayPause {
            get {
                return ResourceManager.GetString("KeyMediaPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Track.
        /// </summary>
        public static string KeyMediaPreviousTrack {
            get {
                return ResourceManager.GetString("KeyMediaPreviousTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string KeyMediaStop {
            get {
                return ResourceManager.GetString("KeyMediaStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Pad {0}.
        /// </summary>
        public static string KeyNumberPad {
            get {
                return ResourceManager.GetString("KeyNumberPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num Lock.
        /// </summary>
        public static string KeyNumLock {
            get {
                return ResourceManager.GetString("KeyNumLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Down.
        /// </summary>
        public static string KeyPageDown {
            get {
                return ResourceManager.GetString("KeyPageDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Up.
        /// </summary>
        public static string KeyPageUp {
            get {
                return ResourceManager.GetString("KeyPageUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string KeyPause {
            get {
                return ResourceManager.GetString("KeyPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Screen.
        /// </summary>
        public static string KeyPrintScreen {
            get {
                return ResourceManager.GetString("KeyPrintScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Arrow.
        /// </summary>
        public static string KeyRightArrow {
            get {
                return ResourceManager.GetString("KeyRightArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Lock.
        /// </summary>
        public static string KeyScrollLock {
            get {
                return ResourceManager.GetString("KeyScrollLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Media.
        /// </summary>
        public static string KeySelectMedia {
            get {
                return ResourceManager.GetString("KeySelectMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string KeyShift {
            get {
                return ResourceManager.GetString("KeyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift (Left).
        /// </summary>
        public static string KeyShiftLeft {
            get {
                return ResourceManager.GetString("KeyShiftLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift (Right).
        /// </summary>
        public static string KeyShiftRight {
            get {
                return ResourceManager.GetString("KeyShiftRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space.
        /// </summary>
        public static string KeySpace {
            get {
                return ResourceManager.GetString("KeySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string KeyTab {
            get {
                return ResourceManager.GetString("KeyTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Arrow.
        /// </summary>
        public static string KeyUpArrow {
            get {
                return ResourceManager.GetString("KeyUpArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Down.
        /// </summary>
        public static string KeyVolumeDown {
            get {
                return ResourceManager.GetString("KeyVolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Mute.
        /// </summary>
        public static string KeyVolumeMute {
            get {
                return ResourceManager.GetString("KeyVolumeMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Up.
        /// </summary>
        public static string KeyVolumeUp {
            get {
                return ResourceManager.GetString("KeyVolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows (Left).
        /// </summary>
        public static string KeyWindowsLeft {
            get {
                return ResourceManager.GetString("KeyWindowsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows (Right).
        /// </summary>
        public static string KeyWindowsRight {
            get {
                return ResourceManager.GetString("KeyWindowsRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string KeyZoom {
            get {
                return ResourceManager.GetString("KeyZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string LocalizationHelper_ReadableSize_B {
            get {
                return ResourceManager.GetString("LocalizationHelper_ReadableSize_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EB.
        /// </summary>
        public static string LocalizationHelper_ReadableSize_EB {
            get {
                return ResourceManager.GetString("LocalizationHelper_ReadableSize_EB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string LocalizationHelper_ReadableSize_GB {
            get {
                return ResourceManager.GetString("LocalizationHelper_ReadableSize_GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        public static string LocalizationHelper_ReadableSize_KB {
            get {
                return ResourceManager.GetString("LocalizationHelper_ReadableSize_KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string LocalizationHelper_ReadableSize_MB {
            get {
                return ResourceManager.GetString("LocalizationHelper_ReadableSize_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB.
        /// </summary>
        public static string LocalizationHelper_ReadableSize_PB {
            get {
                return ResourceManager.GetString("LocalizationHelper_ReadableSize_PB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        public static string LocalizationHelper_ReadableSize_TB {
            get {
                return ResourceManager.GetString("LocalizationHelper_ReadableSize_TB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIMITED.
        /// </summary>
        public static string MarkLimited {
            get {
                return ResourceManager.GetString("MarkLimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW.
        /// </summary>
        public static string MarkNew {
            get {
                return ResourceManager.GetString("MarkNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate link.
        /// </summary>
        public static string NavigateLink {
            get {
                return ResourceManager.GetString("NavigateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation failed.
        /// </summary>
        public static string NavigationFailed {
            get {
                return ResourceManager.GetString("NavigationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to navigate to {0}, could not find a ModernFrame target &apos;{1}&apos;.
        /// </summary>
        public static string NavigationFailedFrameNotFound {
            get {
                return ResourceManager.GetString("NavigationFailedFrameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to navigate to {0}, no source specified.
        /// </summary>
        public static string NavigationFailedSourceNotSpecified {
            get {
                return ResourceManager.GetString("NavigationFailedSourceNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a color.
        /// </summary>
        public static string PickColor {
            get {
                return ResourceManager.GetString("PickColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick any color from screen.
        /// </summary>
        public static string PickColorFromScreen {
            get {
                return ResourceManager.GetString("PickColorFromScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a color.
        /// </summary>
        public static string SelectColor {
            get {
                return ResourceManager.GetString("SelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        public static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace.
        /// </summary>
        public static string StackTrace {
            get {
                return ResourceManager.GetString("StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [url=cmd://copy]Copy[/url] the error details to the clipboard. Try to [url=cmd://refresh]refresh[/url] this page or go [url=cmd://browseback]back[/url]..
        /// </summary>
        public static string SuggestionsMessage {
            get {
                return ResourceManager.GetString("SuggestionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDS &amp; TIFF Files|*.dds;*.tif;*.tiff|Image Files|*.dds;*.tif;*.tiff;*.jpg;*.jpeg;*.png|All files (*.*)|*.*.
        /// </summary>
        public static string TexturesFilter {
            get {
                return ResourceManager.GetString("TexturesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation requires the UI thread.
        /// </summary>
        public static string UIThreadRequired {
            get {
                return ResourceManager.GetString("UIThreadRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token.
        /// </summary>
        public static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operating system.
        /// </summary>
        public static string UnknownOS {
            get {
                return ResourceManager.GetString("UnknownOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown token type.
        /// </summary>
        public static string UnknownTokenType {
            get {
                return ResourceManager.GetString("UnknownTokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newer version {0} is ready to be installed.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
